/*******************************************************************
 *                                                                 *
 *  ROTINA : E X T E N S O                                         *
 *  DATA   : 20/02/2001                                            *
 *  AUTOR  : Elieser Morais                                        *
 *                                                                 *
 *******************************************************************/

ALTER TABLE SISCONFIG ADD
  MOEDASINGULAR   STR40_VALIDO!
ALTER TABLE SISCONFIG ADD
  MOEDAPLURAL     STR40_VALIDO!
ALTER TABLE SISCONFIG ADD
  CENTAVOSINGULAR STR40_VALIDO!
ALTER TABLE SISCONFIG ADD
  CENTAVOPLURAL   STR40_VALIDO!

ALTER TABLE SISCONFIG ADD
  NOTA_PADRAO      INTEIRO!
ALTER TABLE SISCONFIG ADD
  OSABERTA_PADRAO  INTEIRO!
ALTER TABLE SISCONFIG ADD
  OSFECHADA_PADRAO INTEIRO!

ALTER TABLE SISCONFIG ADD
  MEDIDA_SER       INTEIRO!
ALTER TABLE SISCONFIG ADD
  GRUPO_SER        INTEIRO!

ALTER TABLE SISCONFIG ADD
  PRINT_BOLETO     STR60!

UPDATE
  SISCONFIG
SET
  MOEDASINGULAR   = 'REAL',
  MOEDAPLURAL     = 'REAIS',
  CENTAVOSINGULAR = 'CENTAVO',
  CENTAVOPLURAL   = 'CENTAVOS'!

ALTER TABLE DOCUMENTOS ADD
  NUMIMPBOLETO      INTEIRO!

DROP TRIGGER MOVIMENTOS_AFTINS!

DROP TRIGGER MOVIMENTOS_AFTUPD!

DROP PROCEDURE GERAPARCELAS!

DROP VIEW CONFIG_PADRAO!

CREATE VIEW CONFIG_PADRAO(
    CODIGO,
    CODCLIENTE,
    CODCONTA_COMPRACRE,
    CODCONTA_COMPRADEB,
    CODCONTA_VENDACRE,
    CODCONTA_VENDADEB,
    CODCLIENTE_PADRAO,
    VALOR_LIMITE,
    ALIQUOTA_ISS,
    ALIQUOTA_ICMSSIMPLES,
    ICMSSIMPLES,
    CODDOC_AVISTA,
    CODDOC_PRAZO,
    MDI,
    AUTOLAUNCH,
    AUTOLAUNCH_TIME,
    PADRAO,
    PRINT_OS,
    PRINT_NOTA,
    PRINT_BOLETO,
    MOEDASINGULAR,
    MOEDAPLURAL,
    CENTAVOSINGULAR,
    CENTAVOPLURAL,
    NOTA_PADRAO,
    OSABERTA_PADRAO,
    OSFECHADA_PADRAO,
    MEDIDA_SER,
    GRUPO_SER)
AS
SELECT
	SISCONFIG.CODIGO,
	SISCONFIG.CODCLIENTE,
	SISCONFIG.CODCONTA_COMPRACRE,
	SISCONFIG.CODCONTA_COMPRADEB,
	SISCONFIG.CODCONTA_VENDACRE,
	SISCONFIG.CODCONTA_VENDADEB,
	SISCONFIG.CODCLIENTE_PADRAO,
	SISCONFIG.VALOR_LIMITE,
	SISCONFIG.ALIQUOTA_ISS,
	SISCONFIG.ALIQUOTA_ICMSSIMPLES,
	SISCONFIG.ICMSSIMPLES,
	SISCONFIG.CODDOC_AVISTA,
	SISCONFIG.CODDOC_PRAZO,
	SISCONFIG.MDI,
	SISCONFIG.AUTOLAUNCH,
	SISCONFIG.AUTOLAUNCH_TIME,
	SISCONFIG.PADRAO,
	SISCONFIG.PRINT_OS,
	SISCONFIG.PRINT_NOTA,
  	SISCONFIG.PRINT_BOLETO,
      SISCONFIG.MOEDASINGULAR,
      SISCONFIG.MOEDAPLURAL,
      SISCONFIG.CENTAVOSINGULAR,
      SISCONFIG.CENTAVOPLURAL,
      SISCONFIG.NOTA_PADRAO,
      SISCONFIG.OSABERTA_PADRAO,
      SISCONFIG.OSFECHADA_PADRAO,
      SISCONFIG.MEDIDA_SER,
      SISCONFIG.GRUPO_SER
FROM
	SISCONFIG
WHERE
	SISCONFIG.PADRAO = 'S'
!

GRANT SELECT ON CONFIG_PADRAO TO PUBLIC!

CREATE PROCEDURE GERAPARCELAS (
    CODIGO INTEGER)
AS
   DECLARE VARIABLE TOTAL      NUMERIC(9, 2);
   DECLARE VARIABLE PARCELA    NUMERIC(9, 2);
   DECLARE VARIABLE CONDICAO   VARCHAR(40);
   DECLARE VARIABLE QUANTIDADE INTEGER;
   DECLARE VARIABLE ES         INTEGER;
   DECLARE VARIABLE N          INTEGER;
   DECLARE VARIABLE CODPAG     INTEGER;
   DECLARE VARIABLE DATAMOV    DATE;
   DECLARE VARIABLE DIAS       INTEGER;
   DECLARE VARIABLE CODDOC     INTEGER;
   DECLARE VARIABLE CODPAGO    INTEGER;
   DECLARE VARIABLE DOCVISTA   INTEGER;
   DECLARE VARIABLE DOCPRAZO   INTEGER;
   DECLARE VARIABLE DESCRICAO  CHAR(40);
BEGIN
   SELECT
      CODDOC_AVISTA,
      CODDOC_PRAZO
   FROM
      CONFIG_PADRAO
   INTO
      :DOCVISTA,
      :DOCPRAZO;
   SELECT
      VALOR_TOTAL,
      CONDICAO,
      ES,
      DATA
   FROM
      MOVIMENTOS
   WHERE
      CODIGO = :CODIGO
   INTO
      :TOTAL,
      :CONDICAO,
      :ES,
      :DATAMOV;
   IF (TOTAL <= 0) THEN EXIT;
   SELECT
      COUNT(*)
   FROM
      PARCELAS(
        :CONDICAO
      )
   INTO
      :QUANTIDADE;
   IF (QUANTIDADE > 0) THEN
    BEGIN
     DELETE FROM
      PAGAMENTOS
     WHERE
      CODMOVIMENTO = :CODIGO;
     PARCELA = CAST((TOTAL / QUANTIDADE) AS INTEGER);
     N = 0;
     FOR
     SELECT DIAS FROM PARCELAS(:CONDICAO) INTO :DIAS DO
      BEGIN
       N = N + 1;
       IF (ES = 1) THEN
          DESCRICAO = 'PARCELA ' || N || '/' || QUANTIDADE || ' DA COMPRA ' || CODIGO;
       ELSE
          DESCRICAO = 'PARCELA ' || N || '/' || QUANTIDADE || ' DA VENDA ' || CODIGO;
       SELECT SEQUENCIA + 1 FROM SEQUENCIA WHERE TABELA = 'PAGAMENTOS' INTO :CODPAG;
       UPDATE SEQUENCIA SET SEQUENCIA = :CODPAG WHERE TABELA = 'PAGAMENTOS';
       if (DIAS = 0) then
        begin
          CODDOC = DOCVISTA;
          CODPAGO = 1;
        end else
        begin
          CODDOC = DOCPRAZO;
          CODPAGO = 0;
        end
       INSERT INTO PAGAMENTOS (CODIGO, CODMOVIMENTO, NUMERO, DESCRICAO, ES,
         VALOR, DATAVENCIMENTO, CODDOCUMENTO, PAGO) VALUES (:CODPAG, :CODIGO, :N,
         :DESCRICAO, :ES, :PARCELA, :DATAMOV + :DIAS, :CODDOC, :CODPAGO);
      END
     UPDATE PAGAMENTOS SET VALOR = VALOR + (:TOTAL - (:PARCELA * :QUANTIDADE))
       WHERE CODMOVIMENTO = :CODIGO AND NUMERO = 1;
    END ELSE EXCEPTION CONDICAO_ERRADA;
END!

GRANT EXECUTE ON PROCEDURE GERAPARCELAS TO PUBLIC!

CREATE TRIGGER MOVIMENTOS_AFTINS FOR MOVIMENTOS
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
  IF ((NEW.ES IN (1, 2)) AND (NEW.TIPO IN (1, 2, 5)))THEN
    IF (NEW.VALOR_TOTAL > 0) THEN
      EXECUTE PROCEDURE GERAPARCELAS(NEW.CODIGO);
END!

CREATE TRIGGER MOVIMENTOS_AFTUPD FOR MOVIMENTOS
ACTIVE AFTER UPDATE POSITION 0
AS
BEGIN
  IF ((NEW.ES IN (1, 2)) AND (NEW.TIPO IN (1, 2, 5)))THEN
   IF ((NEW.VALOR_TOTAL <> OLD.VALOR_TOTAL) OR
      (NEW.CONDICAO <> OLD.CONDICAO)) THEN
     EXECUTE PROCEDURE GERAPARCELAS(NEW.CODIGO);
  IF (NEW.ES = 9) THEN
     DELETE FROM PAGAMENTOS WHERE CODMOVIMENTO = NEW.CODIGO;
END!

CREATE PROCEDURE VALEXTCONST
RETURNS (
    VALOR DOUBLE PRECISION,
    CONSTSING VARCHAR(40),
    CONSTPLUR VARCHAR(40),
    UNITARIO CHAR(1),
    VIRGULA CHAR(1))
AS
BEGIN
  VALOR     = 1000000000;
  CONSTSING = 'BILHAO';
  CONSTPLUR = 'BILHOES';
  UNITARIO  = 'S';
  VIRGULA   = 'S';
  SUSPEND;
  VALOR     = 1000000;
  CONSTSING = 'MILHAO';
  CONSTPLUR = 'MILHOES';
  UNITARIO  = 'S';
  VIRGULA   = 'S';
  SUSPEND;
  VALOR     = 1000;
  CONSTSING = 'MIL';
  CONSTPLUR = 'MIL';
  UNITARIO  = 'S';
  VIRGULA   = 'S';
  SUSPEND;
  VALOR     = 900;
  CONSTSING = 'NOVECENTOS';
  CONSTPLUR = 'NOVECENTOS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 800;
  CONSTSING = 'OITOCENTOS';
  CONSTPLUR = 'OITOCENTOS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 700;
  CONSTSING = 'SETECENTOS';
  CONSTPLUR = 'SETECENTOS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 600;
  CONSTSING = 'SEISCENTOS';
  CONSTPLUR = 'SEISCENTOS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 500;
  CONSTSING = 'QUINHENTOS';
  CONSTPLUR = 'QUINHENTOS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 400;
  CONSTSING = 'QUATROCENTOS';
  CONSTPLUR = 'QUATROCENTOS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 300;
  CONSTSING = 'TREZENTOS';
  CONSTPLUR = 'TREZENTOS';
  VIRGULA   = 'N';
  UNITARIO  = 'N';
  SUSPEND;
  VALOR     = 200;
  CONSTSING = 'DUZENTOS';
  CONSTPLUR = 'DUZENTOS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 100;
  CONSTSING = 'CEM';
  CONSTPLUR = 'CENTO';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 90;
  CONSTSING = 'NOVENTA';
  CONSTPLUR = 'NOVENTA';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 80;
  CONSTSING = 'OITENTA';
  CONSTPLUR = 'OITENTA';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 70;
  CONSTSING = 'SETENTA';
  CONSTPLUR = 'SETENTA';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 60;
  CONSTSING = 'SESSENTA';
  CONSTPLUR = 'SESSENTA';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 50;
  CONSTSING = 'CINQUENTA';
  CONSTPLUR = 'CINQUENTA';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 40;
  CONSTSING = 'QUARENTA';
  CONSTPLUR = 'QUARENTA';
  VIRGULA   = 'N';
  UNITARIO  = 'N';
  SUSPEND;
  VALOR     = 30;
  CONSTSING = 'TRINTA';
  CONSTPLUR = 'TRINTA';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 20;
  CONSTSING = 'VINTE';
  CONSTPLUR = 'VINTE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 19;
  CONSTSING = 'DEZENOVE';
  CONSTPLUR = 'DEZENOVE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 18;
  CONSTSING = 'DEZOITO';
  CONSTPLUR = 'DEZOITO';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 17;
  CONSTSING = 'DEZESSETE';
  CONSTPLUR = 'DEZESSETE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 16;
  CONSTSING = 'DEZESSEIS';
  CONSTPLUR = 'DEZESSEIS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 15;
  CONSTSING = 'QUINZE';
  CONSTPLUR = 'QUINZE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 14;
  CONSTSING = 'CATORZE';
  CONSTPLUR = 'CATORZE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 13;
  CONSTSING = 'TREZE';
  CONSTPLUR = 'TREZE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 12;
  CONSTSING = 'DOZE';
  CONSTPLUR = 'DOZE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 11;
  CONSTSING = 'ONZE';
  CONSTPLUR = 'ONZE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 10;
  CONSTSING = 'DEZ';
  CONSTPLUR = 'DEZ';
  VIRGULA   = 'N';
  UNITARIO  = 'N';
  SUSPEND;
  VALOR     = 9;
  CONSTSING = 'NOVE';
  CONSTPLUR = 'NOVE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 8;
  CONSTSING = 'OITO';
  CONSTPLUR = 'OITO';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 7;
  CONSTSING = 'SETE';
  CONSTPLUR = 'SETE';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 6;
  CONSTSING = 'SEIS';
  CONSTPLUR = 'SEIS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 5;
  CONSTSING = 'CINCO';
  CONSTPLUR = 'CINCO';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 4;
  CONSTSING = 'QUATRO';
  CONSTPLUR = 'QUATRO';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 3;
  CONSTSING = 'TRES';
  CONSTPLUR = 'TRES';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 2;
  CONSTSING = 'DOIS';
  CONSTPLUR = 'DOIS';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
  VALOR     = 1;
  CONSTSING = 'UM';
  CONSTPLUR = 'UM';
  UNITARIO  = 'N';
  VIRGULA   = 'N';
  SUSPEND;
END!

GRANT EXECUTE ON PROCEDURE VALEXTCONST TO PUBLIC!

CREATE PROCEDURE VALOREXTENSO (
    VALOR DOUBLE PRECISION)
RETURNS (
    EXTENSO VARCHAR(254))
AS
  DECLARE VARIABLE CONSTVAL        DOUBLE PRECISION;
  DECLARE VARIABLE CONSTSING       VARCHAR(40);
  DECLARE VARIABLE CONSTPLUR       VARCHAR(40);
  DECLARE VARIABLE UNITARIO        CHAR(1);
  DECLARE VARIABLE VIRGULA         CHAR(1);
  DECLARE VARIABLE UNIDADE         INTEGER;
  DECLARE VARIABLE TEMPCONST       VARCHAR(254);
BEGIN

  /* INICIALIZO O RETORNO */
  EXTENSO = '';

 FOR
  SELECT
    VALOR,
    CONSTSING,
    CONSTPLUR,
    UNITARIO,
    VIRGULA
  FROM
    VALEXTCONST
  ORDER BY
    VALOR DESC
  INTO
    :CONSTVAL,
    :CONSTSING,
    :CONSTPLUR,
    :UNITARIO,
    :VIRGULA
  DO
  BEGIN

    /* ENCONTRO A UNIDADE DE CADA UM */
    UNIDADE = F_TRUNCATE( VALOR / CONSTVAL );

    /* EH NECESSARIO? */
    IF ( UNIDADE >= 1 ) THEN
     BEGIN

      /* RETIRO O VALOR QUE FOI EXTENDIDO */
    VALOR = VALOR - ( CONSTVAL * UNIDADE );

       /* PREFIXO: EX. 9 MIL REAIS */
       IF ( UNITARIO = 'S' ) THEN
        BEGIN

         EXECUTE PROCEDURE
          VALOREXTENSO( :UNIDADE )
         RETURNING_VALUES
          TEMPCONST;

         EXTENSO = EXTENSO || TEMPCONST || ' ';

        END

       /* COLOCO A CONSTANTE */
       IF (( UNIDADE > 1 ) OR
           /* O NUMERO 100 EH UM CASO ESPECIAL */
        ( UNIDADE = 1 AND CONSTVAL = 100 AND F_TRUNCATE(VALOR) > 0 )) THEN
        EXTENSO = EXTENSO || CONSTPLUR;
       ELSE
        EXTENSO = EXTENSO || CONSTSING;

     /* COLOCO O "E" SE FOR NECESSARIO */
       IF ( F_TRUNCATE(VALOR) > 0 ) THEN
        IF ( VIRGULA = 'S' ) THEN
         EXTENSO = EXTENSO || ', ';
        ELSE
         EXTENSO = EXTENSO || ' E ';

   END

  END

 SUSPEND;

END!

GRANT EXECUTE ON PROCEDURE VALOREXTENSO TO PUBLIC!

CREATE PROCEDURE MOEDAEXTENSO (
    VALOR DOUBLE PRECISION)
RETURNS (
    EXTENSO VARCHAR(254))
AS
  DECLARE VARIABLE MOEDA           VARCHAR(40);
  DECLARE VARIABLE CENTAVO         VARCHAR(40);
  DECLARE VARIABLE MOEDASINGULAR   VARCHAR(40);
  DECLARE VARIABLE MOEDAPLURAL     VARCHAR(40);
  DECLARE VARIABLE CENTAVOSINGULAR VARCHAR(40);
  DECLARE VARIABLE CENTAVOPLURAL   VARCHAR(40);
  DECLARE VARIABLE VALTEMP         INTEGER;
  DECLARE VARIABLE CENTEMP         INTEGER;
  DECLARE VARIABLE TEMPCONST       VARCHAR(254);
BEGIN

  /* PEGO A MOEDA */
  SELECT
    MOEDASINGULAR,
    MOEDAPLURAL,
    CENTAVOSINGULAR,
    CENTAVOPLURAL
  FROM
    CONFIG_PADRAO
  INTO
    :MOEDASINGULAR,
    :MOEDAPLURAL,
    :CENTAVOSINGULAR,
    :CENTAVOPLURAL;

  MOEDA   = '';
  CENTAVO = '';

  /* VALOR INTEIRO */
 VALTEMP = F_TRUNCATE ( VALOR );

  IF ( VALTEMP > 0 ) THEN
   IF ( VALTEMP = 1 ) THEN
    MOEDA = MOEDASINGULAR;
   ELSE
    MOEDA = MOEDAPLURAL;

 /* BUSCO O EXTENSO */
 EXECUTE PROCEDURE
    VALOREXTENSO( :VALTEMP )
  RETURNING_VALUES
    :EXTENSO;

  EXTENSO = EXTENSO || ' ' || MOEDA;

  /* CENTAVOS */
  VALOR   = VALOR - VALTEMP;
  CENTEMP = CAST(( VALOR * 100 ) AS INTEGER);

  IF ( CENTEMP > 0 ) THEN
   BEGIN
    IF ( CENTEMP = 1 ) THEN
     CENTAVO = CENTAVOSINGULAR;
    ELSE
     CENTAVO = CENTAVOPLURAL;

    /* BUSCO O EXTENSO */
    EXECUTE PROCEDURE
      VALOREXTENSO( :CENTEMP )
    RETURNING_VALUES
      :TEMPCONST;

    IF ( VALTEMP > 0 ) THEN
     EXTENSO = EXTENSO || ' E ' || TEMPCONST || ' ' || CENTAVO;
    ELSE
      EXTENSO = TEMPCONST || ' ' || CENTAVO || ' DE ' || MOEDASINGULAR;
   END

  SUSPEND;

END!

GRANT EXECUTE ON PROCEDURE MOEDAEXTENSO TO PUBLIC!

/*******************************************************************
 *                                                                 *
 *  ROTINA : C A M P O S    D E   C O N F I G U R A C A O          *
 *  DATA   : 20/02/2001                                            *
 *  AUTOR  : Elieser Morais                                        *
 *                                                                 *
 *******************************************************************/

CREATE PROCEDURE PROC_PARAMS (
  NOMEPROC  CHAR(31)
)
RETURNS (
  NUMERO      INTEGER,
  NOME        CHAR(31),
  TAMANHO     INTEGER,
  ENTSAI      CHAR(1)
)
AS
  DECLARE VARIABLE TIPO_ES INTEGER;
BEGIN

  FOR
  SELECT
    PP.RDB$PARAMETER_NUMBER,
    PP.RDB$PARAMETER_NAME,
    PP.RDB$PARAMETER_TYPE,
    FD.RDB$CHARACTER_LENGTH
  FROM
    RDB$PROCEDURE_PARAMETERS PP
    JOIN RDB$FIELDS FD ON
      ( PP.RDB$FIELD_SOURCE = FD.RDB$FIELD_NAME )
  WHERE
    RDB$PROCEDURE_NAME = :NOMEPROC
  INTO
    NUMERO,
    NOME,
    TIPO_ES,
    TAMANHO
  DO
  BEGIN
    IF ( TIPO_ES = 0 ) THEN
      ENTSAI = 'E';
    ELSE
      ENTSAI = 'S';

    /* FORCO O TAMANHO 10 PARA TODOS OS CAMPOS NUMERICOS */
    IF ( TAMANHO IS NULL ) THEN
      TAMANHO = 10;
    SUSPEND;
  END

END!

GRANT EXECUTE ON PROCEDURE PROC_PARAMS TO PUBLIC!

/*******************************************************************
 *                                                                 *
 *  ROTINA : N O T A S    F I S C A I S                            *
 *  DATA   : 20/02/2001                                            *
 *  AUTOR  : Elieser Morais                                        *
 *                                                                 *
 *******************************************************************/

CREATE DOMAIN STRALINHA CHAR(1) DEFAULT 'E' NOT NULL
	CHECK (VALUE IN ('D', 'E', 'C'))!

CREATE EXCEPTION IMPNOTA_POSICAO
	'Já existe um campo ocupando este espaço.'!

CREATE TABLE IMPNOTA (
  NUMIMPNOTA  	    INTEIRO_VALIDO,
  DESCRICAO         STR60_VALIDO,
  LINHA18           SIMNAO,
  ALTURA            INTCURTO_CHEIO1,
  DUP_LINHAINI      INTCURTO_CHEIO1,
  DUP_COLUNAS	    INTCURTO_CHEIO1,
  DUP_TAMANHOCOL    INTCURTO_CHEIO1,
  DUP_LINHAS	    INTCURTO_CHEIO1,
  PRO_LINHAINI      INTCURTO_CHEIO1,
  PRO_LINHAS        INTCURTO_CHEIO1,
  SER_LINHAINI      INTCURTO_CHEIO1,
  SER_LINHAS        INTCURTO_CHEIO1,
  CONSTRAINT        IMPNOTA_PK
  PRIMARY KEY       ( NUMIMPNOTA )
)!

GRANT ALL ON IMPNOTA TO PUBLIC!

CREATE TABLE ITIMPNOTA (
  NUMIMPNOTA        INTEIRO_VALIDO,
  LINHA             INTCURTO_CHEIO1,
  COLUNA            INTCURTO_CHEIO1,
  CAMPO             STR60_VALIDO,
  TAMANHO           INTCURTO_CHEIO1,
  ALTURA            INTCURTO_CHEIO1,
  MASCARA           STR60,
  ALINHAMENTO 	    STRALINHA,
  EFEITO            STR10,
  CONSTRAINT        ITIMPNOTA_PK
  PRIMARY KEY       ( NUMIMPNOTA, LINHA, COLUNA )
)!

GRANT ALL ON ITIMPNOTA TO PUBLIC!

CREATE TABLE ITIMPNOTADUP (
  NUMIMPNOTA        INTEIRO_VALIDO,
  COLUNA            INTCURTO_CHEIO1,
  CAMPO             STR60_VALIDO,
  TAMANHO           INTCURTO_CHEIO1,
  ALTURA            INTCURTO_CHEIO1,
  MASCARA           STR60,
  ALINHAMENTO 	    STRALINHA,
  EFEITO            STR10,
  CONSTRAINT        ITIMPNOTADUP_PK
  PRIMARY KEY       ( NUMIMPNOTA, COLUNA )
)!

GRANT ALL ON ITIMPNOTADUP TO PUBLIC!

CREATE TABLE ITIMPNOTAPRO (
  NUMIMPNOTA        INTEIRO_VALIDO,
  COLUNA            INTCURTO_CHEIO1,
  CAMPO             STR60_VALIDO,
  TAMANHO           INTCURTO_CHEIO1,
  ALTURA            INTCURTO_CHEIO1,
  MASCARA           STR60,
  ALINHAMENTO 	    STRALINHA,
  EFEITO            STR10,
  CONSTRAINT        ITIMPNOTAPRO_PK
  PRIMARY KEY       ( NUMIMPNOTA, COLUNA )
)!

GRANT ALL ON ITIMPNOTAPRO TO PUBLIC!

CREATE TABLE ITIMPNOTASER (
  NUMIMPNOTA        INTEIRO_VALIDO,
  COLUNA            INTCURTO_CHEIO1,
  CAMPO             STR60_VALIDO,
  TAMANHO           INTCURTO_CHEIO1,
  ALTURA            INTCURTO_CHEIO1,
  MASCARA           STR60,
  ALINHAMENTO 	    STRALINHA,
  EFEITO            STR10,
  CONSTRAINT        ITIMPNOTASER_PK
  PRIMARY KEY       ( NUMIMPNOTA, COLUNA )
)!

GRANT ALL ON ITIMPNOTASER TO PUBLIC!

CREATE TRIGGER IMPNOTA_BEFINS01 FOR IMPNOTA
ACTIVE BEFORE INSERT POSITION 100
AS
  DECLARE VARIABLE NUMERO INTEGER;
BEGIN
  SELECT
    MAX(NUMIMPNOTA) + 1
  FROM
    IMPNOTA
  INTO
    :NUMERO;
  IF ( NUMERO IS NULL ) THEN
    NUMERO = 1;
  NEW.NUMIMPNOTA = NUMERO;
END!

CREATE TRIGGER ITIMPNOTA_BEFINS01 FOR ITIMPNOTA
ACTIVE BEFORE INSERT POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPNOTA
  WHERE
    NUMIMPNOTA    = NEW.NUMIMPNOTA    AND
    LINHA         = NEW.LINHA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPNOTA_BEFUPD01 FOR ITIMPNOTA
ACTIVE BEFORE UPDATE POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    TAMANHO,
    EFEITO
  FROM
    ITIMPNOTA
  WHERE
    NUMIMPNOTA    = NEW.NUMIMPNOTA    AND
    LINHA         = NEW.LINHA         AND
    COLUNA       <> OLD.COLUNA
  INTO
    COLINI,
    TAMANHO,
    EFEITO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPNOTADUP_BEFINS01 FOR ITIMPNOTADUP
ACTIVE BEFORE INSERT POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPNOTADUP
  WHERE
    NUMIMPNOTA    = NEW.NUMIMPNOTA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPNOTADUP_BEFUPD01 FOR ITIMPNOTADUP
ACTIVE BEFORE UPDATE POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPNOTADUP
  WHERE
    NUMIMPNOTA    = NEW.NUMIMPNOTA    AND
    COLUNA       <> OLD.COLUNA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPNOTAPRO_BEFINS01 FOR ITIMPNOTAPRO
ACTIVE BEFORE INSERT POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPNOTAPRO
  WHERE
    NUMIMPNOTA    = NEW.NUMIMPNOTA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPNOTAPRO_BEFUPD01 FOR ITIMPNOTAPRO
ACTIVE BEFORE UPDATE POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPNOTAPRO
  WHERE
    NUMIMPNOTA    = NEW.NUMIMPNOTA    AND
    COLUNA       <> OLD.COLUNA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPNOTASER_BEFINS01 FOR ITIMPNOTASER
ACTIVE BEFORE INSERT POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPNOTASER
  WHERE
    NUMIMPNOTA    = NEW.NUMIMPNOTA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPNOTASER_BEFUPD01 FOR ITIMPNOTASER
ACTIVE BEFORE UPDATE POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPNOTASER
  WHERE
    NUMIMPNOTA    = NEW.NUMIMPNOTA    AND
    COLUNA       <> OLD.COLUNA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE PROCEDURE IMPNOTA_RESUMO (
    NUMIMPNOTA INTEGER
)
RETURNS (
    LINHA SMALLINT,
    COLUNA SMALLINT,
    CAMPO VARCHAR(80),
    TAMANHO SMALLINT,
    ALTURA SMALLINT,
    MASCARA VARCHAR(80),
    ALINHAMENTO CHAR(1),
    EFEITO VARCHAR(10),
    TIPO CHAR(1),
    PROXIMO CHAR(1))
AS
  DECLARE VARIABLE LINHA18		CHAR(1);
  DECLARE VARIABLE DUP_LINHAINI		SMALLINT;
  DECLARE VARIABLE DUP_COLUNAS		SMALLINT;
  DECLARE VARIABLE DUP_TAMANHOCOL 	SMALLINT;
  DECLARE VARIABLE DUP_LINHAS		SMALLINT;
  DECLARE VARIABLE PRO_LINHAINI		SMALLINT;
  DECLARE VARIABLE PRO_LINHAS		SMALLINT;
  DECLARE VARIABLE SER_LINHAINI		SMALLINT;
  DECLARE VARIABLE SER_LINHAS   	SMALLINT;
  DECLARE VARIABLE COLINI       	SMALLINT;
  DECLARE VARIABLE LININI       	SMALLINT;
  DECLARE VARIABLE REGCOUNT     	SMALLINT;
  DECLARE VARIABLE REGTOTAL     	SMALLINT;

BEGIN

  /* NOTA PADRÃO */
  SELECT
	LINHA18,
  	DUP_LINHAINI,
  	DUP_COLUNAS,
    	DUP_TAMANHOCOL,
  	DUP_LINHAS,
  	PRO_LINHAINI,
  	PRO_LINHAS,
  	SER_LINHAINI,
  	SER_LINHAS
  FROM
    IMPNOTA
  WHERE
    NUMIMPNOTA = :NUMIMPNOTA
  INTO
    :LINHA18,
    :DUP_LINHAINI,
    :DUP_COLUNAS,
    :DUP_TAMANHOCOL,
    :DUP_LINHAS,
    :PRO_LINHAINI,
    :PRO_LINHAS,
    :SER_LINHAINI,
    :SER_LINHAS;

  /* CORPO DA NOTA PRIMEIRO */
  TIPO = 'C';
  PROXIMO = 'N';
  FOR
  SELECT
  	LINHA,
  	COLUNA,
  	CAMPO,
  	TAMANHO,
  	ALTURA,
  	MASCARA,
	ALINHAMENTO,
	EFEITO
  FROM
    ITIMPNOTA
  WHERE
    NUMIMPNOTA    = :NUMIMPNOTA
  ORDER BY
    LINHA, COLUNA
  INTO
    :LINHA,
    :COLUNA,
    :CAMPO,
    :TAMANHO,
    :ALTURA,
    :MASCARA,
    :ALINHAMENTO,
    :EFEITO
  DO
    SUSPEND;

  /* PRODUTOS DA NOTA */
  TIPO = 'P';
  LININI = PRO_LINHAINI;
  WHILE ( LININI < ( PRO_LINHAINI + PRO_LINHAS )) DO
   BEGIN

      SELECT
        COUNT(*)
      FROM
        ITIMPNOTAPRO
      WHERE
        NUMIMPNOTA    = :NUMIMPNOTA
      INTO
        :REGTOTAL;

      REGCOUNT = 0;

      FOR
      SELECT
        COLUNA,
        CAMPO,
        TAMANHO,
        ALTURA,
        MASCARA,
        ALINHAMENTO,
        EFEITO
      FROM
        ITIMPNOTAPRO
      WHERE
        NUMIMPNOTA    = :NUMIMPNOTA
      ORDER BY
        COLUNA
      INTO
        :COLUNA,
        :CAMPO,
        :TAMANHO,
        :ALTURA,
        :MASCARA,
        :ALINHAMENTO,
        :EFEITO
      DO
      BEGIN

        /* LIBERO TODOS OS PRODUTOS ATE O NUMERO DE LINHAS LIMITE */
        LINHA = LININI;

        /* SE FOR O ULTIMO, ENVIO SINAL PARA O PROXIMO REGISTRO */
        REGCOUNT = REGCOUNT + 1;
        IF ( REGCOUNT = REGTOTAL ) THEN
          PROXIMO = 'S';
        ELSE
          PROXIMO = 'N';
        SUSPEND;

      END

      LININI = LININI + 1;

    END


  /* SERVIÇOS DA NOTA */
  TIPO = 'S';
  LININI = SER_LINHAINI;
  WHILE ( LININI < ( SER_LINHAINI + SER_LINHAS )) DO
   BEGIN

      SELECT
        COUNT(*)
      FROM
        ITIMPNOTASER
      WHERE
        NUMIMPNOTA    = :NUMIMPNOTA
      INTO
        :REGTOTAL;

      REGCOUNT = 0;

      FOR
      SELECT
        COLUNA,
        CAMPO,
        TAMANHO,
        ALTURA,
        MASCARA,
        ALINHAMENTO,
        EFEITO
      FROM
        ITIMPNOTASER
      WHERE
        NUMIMPNOTA    = :NUMIMPNOTA
      ORDER BY
        COLUNA
      INTO
        :COLUNA,
        :CAMPO,
        :TAMANHO,
        :ALTURA,
        :MASCARA,
        :ALINHAMENTO,
        :EFEITO
      DO
      BEGIN

        /* LIBERO TODOS OS SERVIÇOS ATE O NUMERO DE LINHAS LIMITE */
        LINHA = LININI;

	/* SE FOR O ULTIMO, ENVIO SINAL PARA O PROXIMO REGISTRO */
        REGCOUNT = REGCOUNT + 1;
        IF ( REGCOUNT = REGTOTAL ) THEN
          PROXIMO = 'S';
        ELSE
          PROXIMO = 'N';
        SUSPEND;

      END

      LININI = LININI + 1;

    END

  /* DUPLICATAS DA NOTA */
  TIPO = 'D';
  LININI = DUP_LINHAINI;
  WHILE ( LININI < ( DUP_LINHAINI + DUP_LINHAS )) DO
   BEGIN

      COLINI = 0;
      WHILE ( COLINI < DUP_COLUNAS ) DO
        BEGIN

          SELECT
            COUNT(*)
          FROM
            ITIMPNOTADUP
          WHERE
            NUMIMPNOTA    = :NUMIMPNOTA
          INTO
            :REGTOTAL;
          REGCOUNT = 0;

          FOR
          SELECT
            COLUNA,
            CAMPO,
            TAMANHO,
            ALTURA,
            MASCARA,
            ALINHAMENTO,
            EFEITO
          FROM
            ITIMPNOTADUP
          WHERE
            NUMIMPNOTA    = :NUMIMPNOTA
          ORDER BY
            COLUNA
          INTO
            :COLUNA,
            :CAMPO,
            :TAMANHO,
            :ALTURA,
            :MASCARA,
            :ALINHAMENTO,
            :EFEITO
          DO
          BEGIN

            /* CALCULO A LINHA */
            LINHA = LININI;

            /* CALCULO A POSIÇÃO DE ACORDO COM A COLUNA ATUAL */
            COLUNA = COLUNA + ( DUP_TAMANHOCOL * COLINI );

            /* SE FOR O ULTIMO, ENVIO SINAL PARA O PROXIMO REGISTRO */
            REGCOUNT = REGCOUNT + 1;
            IF ( REGCOUNT = REGTOTAL ) THEN
              PROXIMO = 'S';
            ELSE
              PROXIMO = 'N';
            SUSPEND;

          END

          COLINI = COLINI + 1;

        END

      LININI = LININI + 1;

    END

END!

GRANT EXECUTE ON PROCEDURE IMPNOTA_RESUMO TO PUBLIC!

/*******************************************************************
 *                                                                 *
 *  ROTINA : B O L E T O S                                         *
 *  DATA   : 20/02/2001                                            *
 *  AUTOR  : Elieser Morais                                        *
 *                                                                 *
 *******************************************************************/

CREATE TABLE IMPBOLETO (
  NUMIMPBOLETO 		INTEIRO_VALIDO,
  DESCRICAO     	STR60_VALIDO,
  LINHA18           	SIMNAO,
  ALTURA		INTCURTO_CHEIO1,
  CONSTRAINT      	IMPBOLETO_PK
  PRIMARY KEY     	( NUMIMPBOLETO )
)!

GRANT ALL ON IMPBOLETO TO PUBLIC!

CREATE TABLE ITIMPBOLETO (
  NUMIMPBOLETO      INTEIRO_VALIDO,
  LINHA             INTCURTO_CHEIO1,
  COLUNA            INTCURTO_CHEIO1,
  CAMPO             STR60_VALIDO,
  TAMANHO           INTCURTO_CHEIO1,
  ALTURA            INTCURTO_CHEIO1,
  MASCARA           STR60,
  ALINHAMENTO 	    STRALINHA,
  EFEITO            STR10,
  CONSTRAINT        ITIMPBOLETO_PK
  PRIMARY KEY       ( NUMIMPBOLETO, LINHA, COLUNA )
)!

GRANT ALL ON ITIMPBOLETO TO PUBLIC!

CREATE TRIGGER IMPBOLETO_BEFINS01 FOR IMPBOLETO
ACTIVE BEFORE INSERT POSITION 100
AS
  DECLARE VARIABLE NUMERO INTEGER;
BEGIN
  SELECT
    MAX(NUMIMPBOLETO) + 1
  FROM
    IMPBOLETO
  INTO
    :NUMERO;
  IF ( NUMERO IS NULL ) THEN
    NUMERO = 1;
  NEW.NUMIMPBOLETO = NUMERO;
END!

CREATE TRIGGER ITIMPBOLETO_BEFINS01 FOR ITIMPBOLETO
ACTIVE BEFORE INSERT POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPBOLETO
  WHERE
    NUMIMPBOLETO    	= NEW.NUMIMPBOLETO    AND
    LINHA         	= NEW.LINHA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPBOLETO_BEFUPD01 FOR ITIMPBOLETO
ACTIVE BEFORE UPDATE POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    TAMANHO,
    EFEITO
  FROM
    ITIMPBOLETO
  WHERE
    NUMIMPBOLETO    	= NEW.NUMIMPBOLETO    AND
    LINHA         	= NEW.LINHA           AND
    COLUNA       	 <> OLD.COLUNA
  INTO
    COLINI,
    TAMANHO,
    EFEITO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!


CREATE PROCEDURE IMPBOLETO_RESUMO (
    NUMIMPBOLETO INTEGER
)
RETURNS (
    LINHA SMALLINT,
    COLUNA SMALLINT,
    CAMPO VARCHAR(80),
    TAMANHO SMALLINT,
    ALTURA SMALLINT,
    MASCARA VARCHAR(80),
    ALINHAMENTO CHAR(1),
    EFEITO VARCHAR(10),
    LINHA18 CHAR(1),
    ALTURAMAX SMALLINT,
    TIPO CHAR(1),
    PROXIMO CHAR(1))
AS
BEGIN

  /* DUPLICATA PADRÃO */
  SELECT
    LINHA18,
    ALTURA
 FROM
    IMPBOLETO
  WHERE
    NUMIMPBOLETO = :NUMIMPBOLETO
  INTO
    :LINHA18,
    :ALTURAMAX;

 /* CAMPOS DA DUPLICATA */
  TIPO = 'D';
  PROXIMO = 'N';
  FOR
  SELECT
   LINHA,
   COLUNA,
   CAMPO,
   TAMANHO,
   ALTURA,
   MASCARA,
   ALINHAMENTO,
   EFEITO
  FROM
    ITIMPBOLETO
  WHERE
    NUMIMPBOLETO    = :NUMIMPBOLETO
  ORDER BY
    LINHA, COLUNA
  INTO
    :LINHA,
    :COLUNA,
    :CAMPO,
    :TAMANHO,
    :ALTURA,
    :MASCARA,
    :ALINHAMENTO,
    :EFEITO
  DO
    SUSPEND;

END!

GRANT EXECUTE ON PROCEDURE IMPBOLETO_RESUMO TO PUBLIC!


/*******************************************************************
 *                                                                 *
 *  ROTINA : O R D E N S   D E   S E R V I C O                     *
 *  DATA   : 21/02/2001                                            *
 *  AUTOR  : Elieser Morais                                        *
 *                                                                 *
 *******************************************************************/

CREATE TABLE IMPOS (
  NUMIMPOS  	    INTEIRO_VALIDO,
  DESCRICAO         STR60_VALIDO,
  LINHA18           SIMNAO,
  ALTURA            INTCURTO_CHEIO1,
  DUP_LINHAINI      INTCURTO_CHEIO1,
  DUP_COLUNAS	    INTCURTO_CHEIO1,
  DUP_TAMANHOCOL    INTCURTO_CHEIO1,
  DUP_LINHAS	    INTCURTO_CHEIO1,
  PRO_LINHAINI      INTCURTO_CHEIO1,
  PRO_LINHAS        INTCURTO_CHEIO1,
  SER_LINHAINI      INTCURTO_CHEIO1,
  SER_LINHAS        INTCURTO_CHEIO1,
  CONSTRAINT        IMPOS_PK
  PRIMARY KEY       ( NUMIMPOS )
)!

GRANT ALL ON IMPOS TO PUBLIC!

CREATE TABLE ITIMPOS (
  NUMIMPOS        INTEIRO_VALIDO,
  LINHA             INTCURTO_CHEIO1,
  COLUNA            INTCURTO_CHEIO1,
  CAMPO             STR60_VALIDO,
  TAMANHO           INTCURTO_CHEIO1,
  ALTURA            INTCURTO_CHEIO1,
  MASCARA           STR60,
  ALINHAMENTO 	    STRALINHA,
  EFEITO            STR10,
  CONSTRAINT        ITIMPOS_PK
  PRIMARY KEY       ( NUMIMPOS, LINHA, COLUNA )
)!

GRANT ALL ON ITIMPOS TO PUBLIC!

CREATE TABLE ITIMPOSDUP (
  NUMIMPOS        INTEIRO_VALIDO,
  COLUNA            INTCURTO_CHEIO1,
  CAMPO             STR60_VALIDO,
  TAMANHO           INTCURTO_CHEIO1,
  ALTURA            INTCURTO_CHEIO1,
  MASCARA           STR60,
  ALINHAMENTO 	    STRALINHA,
  EFEITO            STR10,
  CONSTRAINT        ITIMPOSDUP_PK
  PRIMARY KEY       ( NUMIMPOS, COLUNA )
)!

GRANT ALL ON ITIMPOSDUP TO PUBLIC!

CREATE TABLE ITIMPOSPRO (
  NUMIMPOS        INTEIRO_VALIDO,
  COLUNA            INTCURTO_CHEIO1,
  CAMPO             STR60_VALIDO,
  TAMANHO           INTCURTO_CHEIO1,
  ALTURA            INTCURTO_CHEIO1,
  MASCARA           STR60,
  ALINHAMENTO 	    STRALINHA,
  EFEITO            STR10,
  CONSTRAINT        ITIMPOSPRO_PK
  PRIMARY KEY       ( NUMIMPOS, COLUNA )
)!

GRANT ALL ON ITIMPOSPRO TO PUBLIC!

CREATE TABLE ITIMPOSSER (
  NUMIMPOS        INTEIRO_VALIDO,
  COLUNA            INTCURTO_CHEIO1,
  CAMPO             STR60_VALIDO,
  TAMANHO           INTCURTO_CHEIO1,
  ALTURA            INTCURTO_CHEIO1,
  MASCARA           STR60,
  ALINHAMENTO 	    STRALINHA,
  EFEITO            STR10,
  CONSTRAINT        ITIMPOSSER_PK
  PRIMARY KEY       ( NUMIMPOS, COLUNA )
)!

GRANT ALL ON ITIMPOSSER TO PUBLIC!

CREATE TRIGGER IMPOS_BEFINS01 FOR IMPOS
ACTIVE BEFORE INSERT POSITION 100
AS
  DECLARE VARIABLE NUMERO INTEGER;
BEGIN
  SELECT
    MAX(NUMIMPOS) + 1
  FROM
    IMPOS
  INTO
    :NUMERO;
  IF ( NUMERO IS NULL ) THEN
    NUMERO = 1;
  NEW.NUMIMPOS = NUMERO;
END!

CREATE TRIGGER ITIMPOS_BEFINS01 FOR ITIMPOS
ACTIVE BEFORE INSERT POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPOS
  WHERE
    NUMIMPOS    = NEW.NUMIMPOS    AND
    LINHA         = NEW.LINHA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPOS_BEFUPD01 FOR ITIMPOS
ACTIVE BEFORE UPDATE POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    TAMANHO,
    EFEITO
  FROM
    ITIMPOS
  WHERE
    NUMIMPOS    = NEW.NUMIMPOS    AND
    LINHA         = NEW.LINHA         AND
    COLUNA       <> OLD.COLUNA
  INTO
    COLINI,
    TAMANHO,
    EFEITO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPOSDUP_BEFINS01 FOR ITIMPOSDUP
ACTIVE BEFORE INSERT POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPOSDUP
  WHERE
    NUMIMPOS    = NEW.NUMIMPOS
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPOSDUP_BEFUPD01 FOR ITIMPOSDUP
ACTIVE BEFORE UPDATE POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPOSDUP
  WHERE
    NUMIMPOS    = NEW.NUMIMPOS    AND
    COLUNA       <> OLD.COLUNA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPOSPRO_BEFINS01 FOR ITIMPOSPRO
ACTIVE BEFORE INSERT POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPOSPRO
  WHERE
    NUMIMPOS    = NEW.NUMIMPOS
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPOSPRO_BEFUPD01 FOR ITIMPOSPRO
ACTIVE BEFORE UPDATE POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPOSPRO
  WHERE
    NUMIMPOS    = NEW.NUMIMPOS    AND
    COLUNA       <> OLD.COLUNA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPOSSER_BEFINS01 FOR ITIMPOSSER
ACTIVE BEFORE INSERT POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPOSSER
  WHERE
    NUMIMPOS    = NEW.NUMIMPOS
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE TRIGGER ITIMPOSSER_BEFUPD01 FOR ITIMPOSSER
ACTIVE BEFORE UPDATE POSITION 100
AS
    DECLARE VARIABLE COLINI INTEGER;
    DECLARE VARIABLE COLFIM INTEGER;
    DECLARE VARIABLE EFEITO CHAR(10);
    DECLARE VARIABLE TAMANHO INTEGER;
BEGIN
  /* VERIFICA SE EXISTE DUPLICIDADE DE COORDENADAS */
  FOR
  SELECT
    COLUNA,
    EFEITO,
    TAMANHO
  FROM
    ITIMPOSSER
  WHERE
    NUMIMPOS    = NEW.NUMIMPOS    AND
    COLUNA       <> OLD.COLUNA
  INTO
    COLINI,
    EFEITO,
    TAMANHO
  DO
  BEGIN

    /* VERIFICO SE EH COMPRIMIDO */
    IF ( EFEITO CONTAINING 'C' ) THEN
      TAMANHO = CAST (( TAMANHO * 0.6 ) AS INTEGER );

    /* VERIFICO SE EH EXPANDIDO */
    IF ( EFEITO CONTAINING 'E' ) THEN
      TAMANHO = TAMANHO * 2;

    /* COLUNA FINAL */
    COLFIM = COLINI + TAMANHO - 1;

    /* VERIFICO SE EXISTE SOBREPOSICAO */
    IF ( NEW.COLUNA BETWEEN :COLINI AND :COLFIM ) THEN
        EXCEPTION IMPNOTA_POSICAO;

  END

END!

CREATE PROCEDURE IMPOS_RESUMO (
    NUMIMPOS INTEGER
)
RETURNS (
    LINHA SMALLINT,
    COLUNA SMALLINT,
    CAMPO VARCHAR(80),
    TAMANHO SMALLINT,
    ALTURA SMALLINT,
    MASCARA VARCHAR(80),
    ALINHAMENTO CHAR(1),
    EFEITO VARCHAR(10),
    TIPO CHAR(1),
    PROXIMO CHAR(1))
AS
  DECLARE VARIABLE LINHA18		CHAR(1);
  DECLARE VARIABLE DUP_LINHAINI		SMALLINT;
  DECLARE VARIABLE DUP_COLUNAS		SMALLINT;
  DECLARE VARIABLE DUP_TAMANHOCOL 	SMALLINT;
  DECLARE VARIABLE DUP_LINHAS		SMALLINT;
  DECLARE VARIABLE PRO_LINHAINI		SMALLINT;
  DECLARE VARIABLE PRO_LINHAS		SMALLINT;
  DECLARE VARIABLE SER_LINHAINI		SMALLINT;
  DECLARE VARIABLE SER_LINHAS   	SMALLINT;
  DECLARE VARIABLE COLINI       	SMALLINT;
  DECLARE VARIABLE LININI       	SMALLINT;
  DECLARE VARIABLE REGCOUNT     	SMALLINT;
  DECLARE VARIABLE REGTOTAL     	SMALLINT;

BEGIN

  /* OS PADRÃO */
  SELECT
	LINHA18,
  	DUP_LINHAINI,
  	DUP_COLUNAS,
    	DUP_TAMANHOCOL,
  	DUP_LINHAS,
  	PRO_LINHAINI,
  	PRO_LINHAS,
  	SER_LINHAINI,
  	SER_LINHAS
  FROM
    IMPOS
  WHERE
    NUMIMPOS = :NUMIMPOS
  INTO
    :LINHA18,
    :DUP_LINHAINI,
    :DUP_COLUNAS,
    :DUP_TAMANHOCOL,
    :DUP_LINHAS,
    :PRO_LINHAINI,
    :PRO_LINHAS,
    :SER_LINHAINI,
    :SER_LINHAS;

  /* CORPO DA OS PRIMEIRO */
  TIPO = 'C';
  PROXIMO = 'N';
  FOR
  SELECT
  	LINHA,
  	COLUNA,
  	CAMPO,
  	TAMANHO,
  	ALTURA,
  	MASCARA,
	ALINHAMENTO,
	EFEITO
  FROM
    ITIMPOS
  WHERE
    NUMIMPOS    = :NUMIMPOS
  ORDER BY
    LINHA, COLUNA
  INTO
    :LINHA,
    :COLUNA,
    :CAMPO,
    :TAMANHO,
    :ALTURA,
    :MASCARA,
    :ALINHAMENTO,
    :EFEITO
  DO
    SUSPEND;

  /* PRODUTOS DA OS */
  TIPO = 'P';
  LININI = PRO_LINHAINI;
  WHILE ( LININI < ( PRO_LINHAINI + PRO_LINHAS )) DO
   BEGIN

      SELECT
        COUNT(*)
      FROM
        ITIMPOSPRO
      WHERE
        NUMIMPOS    = :NUMIMPOS
      INTO
        :REGTOTAL;

      REGCOUNT = 0;

      FOR
      SELECT
        COLUNA,
        CAMPO,
        TAMANHO,
        ALTURA,
        MASCARA,
        ALINHAMENTO,
        EFEITO
      FROM
        ITIMPOSPRO
      WHERE
        NUMIMPOS    = :NUMIMPOS
      ORDER BY
        COLUNA
      INTO
        :COLUNA,
        :CAMPO,
        :TAMANHO,
        :ALTURA,
        :MASCARA,
        :ALINHAMENTO,
        :EFEITO
      DO
      BEGIN

        /* LIBERO TODOS OS PRODUTOS ATE O NUMERO DE LINHAS LIMITE */
        LINHA = LININI;

        /* SE FOR O ULTIMO, ENVIO SINAL PARA O PROXIMO REGISTRO */
        REGCOUNT = REGCOUNT + 1;
        IF ( REGCOUNT = REGTOTAL ) THEN
          PROXIMO = 'S';
        ELSE
          PROXIMO = 'N';
        SUSPEND;

      END

      LININI = LININI + 1;

    END


  /* SERVIÇOS DA OS */
  TIPO = 'S';
  LININI = SER_LINHAINI;
  WHILE ( LININI < ( SER_LINHAINI + SER_LINHAS )) DO
   BEGIN

      SELECT
        COUNT(*)
      FROM
        ITIMPOSSER
      WHERE
        NUMIMPOS    = :NUMIMPOS
      INTO
        :REGTOTAL;

      REGCOUNT = 0;

      FOR
      SELECT
        COLUNA,
        CAMPO,
        TAMANHO,
        ALTURA,
        MASCARA,
        ALINHAMENTO,
        EFEITO
      FROM
        ITIMPOSSER
      WHERE
        NUMIMPOS    = :NUMIMPOS
      ORDER BY
        COLUNA
      INTO
        :COLUNA,
        :CAMPO,
        :TAMANHO,
        :ALTURA,
        :MASCARA,
        :ALINHAMENTO,
        :EFEITO
      DO
      BEGIN

        /* LIBERO TODOS OS SERVIÇOS ATE O NUMERO DE LINHAS LIMITE */
        LINHA = LININI;

	/* SE FOR O ULTIMO, ENVIO SINAL PARA O PROXIMO REGISTRO */
        REGCOUNT = REGCOUNT + 1;
        IF ( REGCOUNT = REGTOTAL ) THEN
          PROXIMO = 'S';
        ELSE
          PROXIMO = 'N';
        SUSPEND;

      END

      LININI = LININI + 1;

    END

  /* DUPLICATAS DA OS */
  TIPO = 'D';
  LININI = DUP_LINHAINI;
  WHILE ( LININI < ( DUP_LINHAINI + DUP_LINHAS )) DO
   BEGIN

      COLINI = 0;
      WHILE ( COLINI < DUP_COLUNAS ) DO
        BEGIN

          SELECT
            COUNT(*)
          FROM
            ITIMPOSDUP
          WHERE
            NUMIMPOS    = :NUMIMPOS
          INTO
            :REGTOTAL;
          REGCOUNT = 0;

          FOR
          SELECT
            COLUNA,
            CAMPO,
            TAMANHO,
            ALTURA,
            MASCARA,
            ALINHAMENTO,
            EFEITO
          FROM
            ITIMPOSDUP
          WHERE
            NUMIMPOS    = :NUMIMPOS
          ORDER BY
            COLUNA
          INTO
            :COLUNA,
            :CAMPO,
            :TAMANHO,
            :ALTURA,
            :MASCARA,
            :ALINHAMENTO,
            :EFEITO
          DO
          BEGIN

            /* CALCULO A LINHA */
            LINHA = LININI;

            /* CALCULO A POSIÇÃO DE ACORDO COM A COLUNA ATUAL */
            COLUNA = COLUNA + ( DUP_TAMANHOCOL * COLINI );

            /* SE FOR O ULTIMO, ENVIO SINAL PARA O PROXIMO REGISTRO */
            REGCOUNT = REGCOUNT + 1;
            IF ( REGCOUNT = REGTOTAL ) THEN
              PROXIMO = 'S';
            ELSE
              PROXIMO = 'N';
            SUSPEND;

          END

          COLINI = COLINI + 1;

        END

      LININI = LININI + 1;

    END

END!

GRANT EXECUTE ON PROCEDURE IMPOS_RESUMO TO PUBLIC!

/*******************************************************************
 *                                                                 *
 *  ROTINA : I N T E G R I D A D E    D O    S I S T E M A         *
 *  DATA   : 21/02/2001                                            *
 *  AUTOR  : Elieser Morais                                        *
 *                                                                 *
 *******************************************************************/

ALTER TABLE SISCONFIG ADD CONSTRAINT SISCONFIG_FK09
        FOREIGN KEY ( NOTA_PADRAO )
        REFERENCES IMPNOTA ( NUMIMPNOTA )
	ON UPDATE CASCADE!

ALTER TABLE SISCONFIG ADD CONSTRAINT SISCONFIG_FK10
        FOREIGN KEY ( OSABERTA_PADRAO )
        REFERENCES IMPOS ( NUMIMPOS )
	ON UPDATE CASCADE!

ALTER TABLE SISCONFIG ADD CONSTRAINT SISCONFIG_FK11
        FOREIGN KEY ( OSFECHADA_PADRAO )
        REFERENCES IMPOS ( NUMIMPOS )
	ON UPDATE CASCADE!

ALTER TABLE DOCUMENTOS ADD CONSTRAINT DOCUMENTOS_FK01
        FOREIGN KEY ( NUMIMPBOLETO )
        REFERENCES IMPBOLETO ( NUMIMPBOLETO )
	ON UPDATE CASCADE!

ALTER TABLE ITIMPNOTA ADD CONSTRAINT ITIMPNOTA_FK01
        FOREIGN KEY ( NUMIMPNOTA )
        REFERENCES IMPNOTA ( NUMIMPNOTA )
	ON UPDATE CASCADE
	ON DELETE CASCADE!

ALTER TABLE ITIMPNOTADUP ADD CONSTRAINT ITIMPNOTADUP_FK01
        FOREIGN KEY ( NUMIMPNOTA )
        REFERENCES IMPNOTA ( NUMIMPNOTA )
	ON UPDATE CASCADE
	ON DELETE CASCADE!

ALTER TABLE ITIMPNOTAPRO ADD CONSTRAINT ITIMPNOTAPRO_FK01
        FOREIGN KEY ( NUMIMPNOTA )
        REFERENCES IMPNOTA ( NUMIMPNOTA )
	ON UPDATE CASCADE
	ON DELETE CASCADE!

ALTER TABLE ITIMPNOTASER ADD CONSTRAINT ITIMPNOTASER_FK01
        FOREIGN KEY ( NUMIMPNOTA )
        REFERENCES IMPNOTA ( NUMIMPNOTA )
	ON UPDATE CASCADE
	ON DELETE CASCADE!

ALTER TABLE ITIMPBOLETO ADD CONSTRAINT ITIMPBOLETO_FK01
        FOREIGN KEY ( NUMIMPBOLETO )
        REFERENCES IMPBOLETO ( NUMIMPBOLETO )
	ON UPDATE CASCADE
	ON DELETE CASCADE!

ALTER TABLE ITIMPOS ADD CONSTRAINT ITIMPOS_FK01
        FOREIGN KEY ( NUMIMPOS )
        REFERENCES IMPOS ( NUMIMPOS )
	ON UPDATE CASCADE
	ON DELETE CASCADE!

ALTER TABLE ITIMPOSDUP ADD CONSTRAINT ITIMPOSDUP_FK01
        FOREIGN KEY ( NUMIMPOS )
        REFERENCES IMPOS ( NUMIMPOS )
	ON UPDATE CASCADE
	ON DELETE CASCADE!

ALTER TABLE ITIMPOSPRO ADD CONSTRAINT ITIMPOSPRO_FK01
        FOREIGN KEY ( NUMIMPOS )
        REFERENCES IMPOS ( NUMIMPOS )
	ON UPDATE CASCADE
	ON DELETE CASCADE!

ALTER TABLE ITIMPOSSER ADD CONSTRAINT ITIMPOSSER_FK01
        FOREIGN KEY ( NUMIMPOS )
        REFERENCES IMPOS ( NUMIMPOS )
	ON UPDATE CASCADE
	ON DELETE CASCADE!

/*******************************************************************
 *                                                                 *
 *  ROTINA : S E R V I C O S     I N D I V I D U A I S             *
 *  DATA   : 20/02/2001                                            *
 *  AUTOR  : Elieser Morais                                        *
 *                                                                 *
 *******************************************************************/

CREATE DOMAIN PS_REQDEF CHAR(1) DEFAULT 'P'
  CHECK (VALUE IN ('P', 'S'))!

ALTER TABLE PRODUTOS ADD
  PS               PS_REQDEF!

ALTER TRIGGER VERIFICA_BARRA_UPD INACTIVE!

UPDATE
  PRODUTOS
SET
  PS = 'P'!

ALTER TRIGGER VERIFICA_BARRA_UPD ACTIVE!

ALTER TABLE INDIVIDUAIS ADD
  PS               PS_REQDEF!

ALTER TRIGGER INDIVIDUAIS_BEFUPD INACTIVE!
ALTER TRIGGER INDIVIDUAIS_AFTUPD INACTIVE!

UPDATE
  INDIVIDUAIS
SET
  PS = 'P'!

ALTER TRIGGER INDIVIDUAIS_BEFUPD ACTIVE!
ALTER TRIGGER INDIVIDUAIS_AFTUPD ACTIVE!

DROP TRIGGER INDIVIDUAIS_AFTINS!

CREATE TRIGGER INDIVIDUAIS_AFTINS FOR INDIVIDUAIS
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
 IF (NEW.PS = 'P') THEN
  IF (NEW.FRACIONADO = 'N') THEN
   BEGIN
    UPDATE PRODUTOS SET QUANTIDADE = QUANTIDADE + NEW.QUANTIDADE
      WHERE CODIGO = NEW.CODPRODUTO;
   END
END!

DROP TRIGGER INDIVIDUAIS_AFTUPD!

CREATE TRIGGER INDIVIDUAIS_AFTUPD FOR INDIVIDUAIS
ACTIVE AFTER UPDATE POSITION 0
AS
BEGIN
 IF (NEW.PS = 'P') THEN
  IF (NEW.VENDIDO <> OLD.VENDIDO) THEN
   BEGIN
    IF (NEW.VENDIDO = 'N') THEN
     BEGIN
      UPDATE PRODUTOS SET QUANTIDADE = QUANTIDADE + NEW.QUANTIDADE
        WHERE CODIGO = NEW.CODPRODUTO;
     END ELSE
     BEGIN
      UPDATE PRODUTOS SET QUANTIDADE = QUANTIDADE - NEW.QUANTIDADE
        WHERE CODIGO = NEW.CODPRODUTO;
     END
   END
END!

DROP TRIGGER INDIVIDUAIS_AFTDEL!

CREATE TRIGGER INDIVIDUAIS_AFTDEL FOR INDIVIDUAIS
ACTIVE AFTER DELETE POSITION 0
AS
BEGIN
 IF (OLD.PS = 'P') THEN
  IF (OLD.VENDIDO = 'N') THEN
   BEGIN
    UPDATE PRODUTOS SET QUANTIDADE = QUANTIDADE - OLD.QUANTIDADE
      WHERE CODIGO = OLD.CODPRODUTO;
   END
END!

DROP TRIGGER ORSOMA_INS!

CREATE TRIGGER ORSOMA_INS FOR TEMPITENS
ACTIVE AFTER INSERT POSITION 0
AS
   DECLARE VARIABLE SOMA       NUMERIC(9,2);
   DECLARE VARIABLE CODIGO     INTEGER;
   DECLARE VARIABLE ES         CHAR(1);
   DECLARE VARIABLE TIPO       CHAR(1);
   DECLARE VARIABLE ETIQUETA   CHAR(1);
   DECLARE VARIABLE NUMETIQ    INTEGER;
   DECLARE VARIABLE INDIVIDUAL CHAR(1);
   DECLARE VARIABLE SEQUENCIA  INTEGER;
   DECLARE VARIABLE SEQUENSTR  CHAR(4);
   DECLARE VARIABLE N          INTEGER;
   DECLARE VARIABLE C          INTEGER;
   DECLARE VARIABLE BARRA      CHAR(14);
   DECLARE VARIABLE PS         CHAR(1);
BEGIN
 /* VERIFICO SE EXISTE CÓDIGO DE BARRAS VÁLIDO */
 SELECT BARRA, PS FROM PRODUTOS WHERE CODIGO = NEW.CODPRODUTO INTO :BARRA, :PS;
 IF (BARRA = '0000000000000') THEN
      EXCEPTION BARRA_NECESSARIA;

 IF (PS = 'P') THEN
  BEGIN

   CODIGO = NEW.CODMOVIMENTO;
   SELECT ES, TIPO FROM MOVIMENTOS WHERE CODIGO = :CODIGO
     INTO :ES, :TIPO;
   IF ((ES = 1) AND (TIPO = 1)) THEN
    BEGIN
      UPDATE PRODUTOS SET PRECOCUSTO = NEW.VALOR_UNITARIO
        WHERE CODIGO = NEW.CODPRODUTO;
      IF (NEW.REAJUSTAR = 'S') THEN
        UPDATE PRODUTOS SET PRECOVENDA = NEW.VALOR_VENDA,
          ICMS = NEW.ICMSVENDA WHERE CODIGO = NEW.CODPRODUTO;
      SELECT ETIQUETA, INDIVIDUAL, SEQUENCIA, BARRA FROM PRODUTOS
        WHERE CODIGO = NEW.CODPRODUTO
        INTO :ETIQUETA, :INDIVIDUAL, :SEQUENCIA, :BARRA;
      N = 0;
      IF (INDIVIDUAL = 'S') THEN
       BEGIN
        WHILE (N < NEW.QUANTIDADE) DO
         BEGIN
           N = N + 1;
           SEQUENCIA = (SEQUENCIA + 1);
           IF (SEQUENCIA > 99) THEN SEQUENSTR = ('0' || SEQUENCIA);
            ELSE IF (SEQUENCIA > 9) THEN SEQUENSTR = ('00' || SEQUENCIA);
             ELSE IF (SEQUENCIA > 0) THEN SEQUENSTR = ('000' || SEQUENCIA);
              ELSE SEQUENSTR = '0000';
           BARRA = EAN('999' || NEW.CODPRODUTO || SEQUENSTR || '0');
           EXECUTE PROCEDURE SEQ_OBTER 'INDIVIDUAIS'
             RETURNING_VALUES C;
           INSERT INTO INDIVIDUAIS (CODIGO, CODITEM, CODPRODUTO, CODMOVENTRADA, SEQUENCIA,
             ICMSVENDA, VALOR_VENDA, IMPETIQ, QUANTIDADE, UNICO, BARRA) VALUES (:C,
             NEW.CODIGO, NEW.CODPRODUTO, NEW.CODMOVIMENTO, :SEQUENSTR, NEW.ICMSVENDA,
             NEW.VALOR_VENDA, :ETIQUETA, 1, 1, :BARRA);
         END
        UPDATE PRODUTOS SET SEQUENCIA = (SEQUENCIA + NEW.QUANTIDADE)
          WHERE CODIGO = NEW.CODPRODUTO;
       END ELSE
       BEGIN
           EXECUTE PROCEDURE SEQ_OBTER 'INDIVIDUAIS'
             RETURNING_VALUES C;
           INSERT INTO INDIVIDUAIS (CODIGO, CODITEM, CODPRODUTO, CODMOVENTRADA, SEQUENCIA,
             ICMSVENDA, VALOR_VENDA, IMPETIQ, QUANTIDADE, UNICO, BARRA) VALUES (:C,
             NEW.CODIGO, NEW.CODPRODUTO, NEW.CODMOVIMENTO, '0000', NEW.ICMSVENDA,
             NEW.VALOR_VENDA, :ETIQUETA, NEW.QUANTIDADE, 0, :BARRA);
       END
    END
   UPDATE MOVIMENTOS SET VALOR_ITENS = VALOR_ITENS + NEW.VALOR_TOTAL
     WHERE CODIGO = :CODIGO;

  END

END!

DROP TRIGGER ORSOMA_DEL!

CREATE TRIGGER ORSOMA_DEL FOR TEMPITENS
ACTIVE BEFORE DELETE POSITION 0
AS
   DECLARE VARIABLE PS CHAR(1);
BEGIN
  SELECT
    PS
  FROM
    PRODUTOS
  WHERE
    CODIGO = OLD.CODPRODUTO
  INTO
    :PS;
  if (PS = 'P') then
   UPDATE MOVIMENTOS SET VALOR_ITENS = VALOR_ITENS - OLD.VALOR_TOTAL
     WHERE CODIGO = OLD.CODMOVIMENTO;
END!

ALTER PROCEDURE ITVENDA_GRAVA (
    BARRA CHAR(14),
    QUANTIDADE NUMERIC(9,2),
    VALOR NUMERIC(9,2),
    DESCONTO NUMERIC(9,2),
    ICMS NUMERIC(9,2),
    CODMOVSAIDA INTEGER)
AS
  DECLARE VARIABLE XCODIGO       INTEGER;
  DECLARE VARIABLE XCODITEM      INTEGER;
  DECLARE VARIABLE XCODPRODUTO   INTEGER;
  DECLARE VARIABLE XCODMOVENTRADA INTEGER;
  DECLARE VARIABLE XSEQUENCIA     CHAR(4);
  DECLARE VARIABLE XSERIE         CHAR(20);
  DECLARE VARIABLE XVENDIDO       CHAR(1);
  DECLARE VARIABLE XCODMOVSAIDA   INTEGER;
  DECLARE VARIABLE XVALOR_VENDA   NUMERIC(9, 2);
  DECLARE VARIABLE XICMSVENDA     NUMERIC(9, 2);
  DECLARE VARIABLE XDESCONTO      NUMERIC(9, 2);
  DECLARE VARIABLE XIMPETIQ       CHAR(1);
  DECLARE VARIABLE XBARRA         CHAR(14);
  DECLARE VARIABLE XQUANTIDADE    NUMERIC(9, 2);
  DECLARE VARIABLE XUNICO         INTEGER;
  DECLARE VARIABLE BAIXA          NUMERIC(9, 2);
  DECLARE VARIABLE SOBRA          NUMERIC(9, 2);
  DECLARE VARIABLE NSEQ           INTEGER;
  DECLARE VARIABLE PS             CHAR(1);
  DECLARE VARIABLE XPRECOCUSTO    NUMERIC(9, 2);
BEGIN
  SELECT
    CODIGO,
    PRECOCUSTO,
    PS
  FROM
    PRODUTOS
  WHERE
    BARRA = :BARRA
  INTO
    :XCODPRODUTO,
    :XPRECOCUSTO,
    :PS;

  IF (PS = 'P') THEN
   BEGIN

    SELECT SUM(QUANTIDADE) FROM INDIVIDUAIS
      WHERE BARRA = :BARRA AND VENDIDO = 'S' AND CODMOVSAIDA = :CODMOVSAIDA
      INTO :XQUANTIDADE;
    IF (XQUANTIDADE IS NULL) THEN XQUANTIDADE = 0;
    IF (XQUANTIDADE > 0) THEN
      EXCEPTION ITEM_REPETIDO;
    SELECT SUM(QUANTIDADE) FROM INDIVIDUAIS
    WHERE BARRA = :BARRA AND VENDIDO = 'N'
    INTO :XQUANTIDADE;
    IF (QUANTIDADE <= XQUANTIDADE) THEN
      BEGIN
        FOR
        SELECT CODIGO, CODITEM, CODPRODUTO, CODMOVENTRADA, SEQUENCIA, SERIE,
          VENDIDO, CODMOVSAIDA, VALOR_VENDA, ICMSVENDA, DESCONTO, IMPETIQ,
          BARRA, QUANTIDADE, UNICO FROM INDIVIDUAIS
          WHERE BARRA = :BARRA AND VENDIDO = 'N' ORDER BY CODIGO
          INTO :XCODIGO, :XCODITEM, :XCODPRODUTO, :XCODMOVENTRADA,
          :XSEQUENCIA, :XSERIE, :XVENDIDO, :XCODMOVSAIDA, :XVALOR_VENDA,
          :XICMSVENDA, :XDESCONTO, :XIMPETIQ, :XBARRA, :XQUANTIDADE, :XUNICO
        DO
        BEGIN
          IF (QUANTIDADE > 0) THEN
            BEGIN
              SOBRA = 0;
              IF (QUANTIDADE >= XQUANTIDADE) THEN
                BEGIN
                  BAIXA = XQUANTIDADE;
                END ELSE
                BEGIN
                  BAIXA = QUANTIDADE;
                  SOBRA = XQUANTIDADE - BAIXA;
                END
              QUANTIDADE = QUANTIDADE - BAIXA;
              UPDATE INDIVIDUAIS SET QUANTIDADE = :BAIXA,
                CODMOVSAIDA = :CODMOVSAIDA, VALOR_VENDA = :VALOR,
                DESCONTO = :DESCONTO, VENDIDO = 'S', ICMSVENDA = :ICMS
                WHERE CODIGO = :XCODIGO;
              IF (SOBRA > 0) THEN
                BEGIN
                  EXECUTE PROCEDURE SEQ_OBTER 'INDIVIDUAIS'
                    RETURNING_VALUES NSEQ;
                  XVENDIDO = 'N';
                  INSERT INTO INDIVIDUAIS (CODIGO, CODITEM, CODPRODUTO,
                    CODMOVENTRADA, SEQUENCIA, SERIE, VENDIDO, VALOR_VENDA,
                    ICMSVENDA, DESCONTO, IMPETIQ, BARRA, QUANTIDADE, UNICO,
                    FRACIONADO) VALUES (:NSEQ, :XCODITEM, :XCODPRODUTO,
                    :XCODMOVENTRADA, :XSEQUENCIA, :XSERIE, :XVENDIDO,
                    :XVALOR_VENDA, :XICMSVENDA, :XDESCONTO, :XIMPETIQ,
                    :XBARRA, :SOBRA, :XUNICO, 'S');
              END
            END ELSE EXIT;
        END
      END ELSE EXCEPTION ITEM_ESGOTADO;

    END ELSE
    BEGIN

      EXECUTE PROCEDURE SEQ_OBTER 'TEMPITENS'
         RETURNING_VALUES XCODITEM;

      INSERT INTO TEMPITENS (CODIGO, CODMOVIMENTO, CODPRODUTO,
         QUANTIDADE, VALOR_UNITARIO, DESCONTO,
         SITTRIBU, MARGEM, REAJUSTAR, VALOR_VENDA,
         ICMSCOMPRA, ICMSVENDA) VALUES (:XCODITEM,
         :CODMOVSAIDA, :XCODPRODUTO, 1, :XPRECOCUSTO,
         0, '0.0', 0, 'N', :VALOR, 0, 0);

      EXECUTE PROCEDURE SEQ_OBTER 'INDIVIDUAIS'
         RETURNING_VALUES NSEQ;

      INSERT INTO INDIVIDUAIS (CODIGO, CODITEM, CODPRODUTO,
         CODMOVENTRADA, CODMOVSAIDA, SEQUENCIA, SERIE, VENDIDO, VALOR_VENDA,
         ICMSVENDA, DESCONTO, IMPETIQ, BARRA, QUANTIDADE, UNICO,
         FRACIONADO, PS) VALUES (:NSEQ, :XCODITEM, :XCODPRODUTO,
         :CODMOVSAIDA, :CODMOVSAIDA, '0000', '', 'S',
         :VALOR, 0, :DESCONTO, 'N',
         :BARRA, 1, 0, 'N', 'S');

    END
END!


ALTER PROCEDURE INFOVENDA (
    BARRA CHAR(14))
RETURNS (
    CODIGO INTEGER,
    QUANTIDADE INTEGER,
    DESCRICAO VARCHAR(100),
    ICMS NUMERIC(9,2),
    VALOR NUMERIC(9,2))
AS
    DECLARE VARIABLE CODPRODUTO INTEGER;
    DECLARE VARIABLE UNICO      INTEGER;
    DECLARE VARIABLE NUMSERIE   CHAR(20);
    declare variable PS         CHAR(1);
BEGIN
  SELECT
    CODIGO,
    PS,
    DESCRICAO,
    PRECOVENDA
  FROM
    PRODUTOS
  WHERE
    BARRA = :BARRA
  INTO
    :CODIGO,
    :PS,
    :DESCRICAO,
    :VALOR;

  if (PS = 'S') then
   begin
    ICMS = 0;
    QUANTIDADE = 9999;
    SUSPEND;
    EXIT;
   end

  SELECT COUNT(*) FROM INDIVIDUAIS WHERE
    BARRA = :BARRA AND VENDIDO = 'N' INTO CODIGO;
  IF (CODIGO IS NULL) THEN CODIGO = 0;
  IF (CODIGO = 0) THEN
     EXCEPTION ITEM_ERRADO;
  FOR
  SELECT INDIVIDUAIS.CODIGO,
         INDIVIDUAIS.CODPRODUTO,
         INDIVIDUAIS.UNICO,
         INDIVIDUAIS.SERIE,
         PRODUTOS.PRECOVENDA,
         PRODUTOS.ICMS,
         PRODUTOS.DESCRICAO
    FROM INDIVIDUAIS
    JOIN PRODUTOS ON (INDIVIDUAIS.CODPRODUTO = PRODUTOS.CODIGO)
   WHERE INDIVIDUAIS.BARRA = :BARRA AND
         INDIVIDUAIS.VENDIDO = 'N' AND
         INDIVIDUAIS.CODPRODUTO = PRODUTOS.CODIGO
    INTO :CODIGO, :CODPRODUTO, :UNICO, :NUMSERIE, :VALOR, :ICMS, :DESCRICAO
  DO
  BEGIN
    IF (UNICO = 1) THEN
     BEGIN
       IF (NUMSERIE IS NOT NULL) THEN
         DESCRICAO = DESCRICAO || ' - ' || NUMSERIE;
       QUANTIDADE = 1;
     END ELSE
     BEGIN
       SELECT SUM(QUANTIDADE)
       FROM INDIVIDUAIS
       WHERE BARRA = :BARRA AND
             VENDIDO = 'N'
       INTO :QUANTIDADE;
     END
    SUSPEND;
    EXIT;
  END
END!

/*******************************************************************
 *                                                                 *
 *  ROTINA : A C E S S O    A O S    D A D O S                     *
 *  DATA   : 20/02/2001                                            *
 *  AUTOR  : Elieser Morais                                        *
 *                                                                 *
 *******************************************************************/

CREATE PROCEDURE REL_NOTACORPO (
   CODMOVIMENTO  INTEGER
)
RETURNS (
    ES				SMALLINT,
    CODCLIENTE                  INTEGER,
    CODFORNECEDOR		INTEGER,
    DATA			DATE,
    SERVICOS			VARCHAR(1024),
    VALOR_SERVICOS		NUMERIC(9, 2),
    VALOR_ITENS			NUMERIC(9, 2),
    DESCONTO			NUMERIC(9, 2),
    VALOR_PRODUTOS		NUMERIC(9, 2),
    VALOR_ICMS			NUMERIC(9, 2),
    VALOR_TOTAL			NUMERIC(9, 2),
    OBSERVACOES			VARCHAR(2048),
    NOTA_NUMERO                 INTEGER,
    NOTA_DATAEMISSAO            TIMESTAMP,
    NOTA_CODNATUOPER            INTEGER,
    NOTA_CODTRANSPORTADOR       INTEGER,
    NOTA_PLACAVEICULO           VARCHAR(10),
    NOTA_UFVEICULO              VARCHAR(2),
    NOTA_FRETE                  SMALLINT,
    NOTA_VALOR_FRETE            NUMERIC(9, 2),
    NOTA_VALOR_SEGURO           NUMERIC(9, 2),
    NOTA_VALOR_OUTROS           NUMERIC(9, 2),
    NOTA_VALOR_TOTAL            NUMERIC(9, 2),
    NOTA_QUANTIDADE             NUMERIC(9, 2),
    NOTA_ESPECIE		VARCHAR(30),
    NOTA_MARCA			VARCHAR(20),
    NOTA_VOLNUM			INTEGER,
    NOTA_PESOBRUTO		NUMERIC(9, 2),
    NOTA_PESOLIQUIDO		NUMERIC(9, 2),
    NOTA_DADOSADICIONAIS	VARCHAR(1024),
    CODVENDEDOR			INTEGER,
    STATUS			VARCHAR(20),
    CONDICAO			VARCHAR(40),
    DATAINICIO			TIMESTAMP,
    DATATERMINO			TIMESTAMP,
    ICMSSIMPLES			CHAR(1),
    ICMSSIMPALIQ		NUMERIC(9, 4),
    ISSALIQ			NUMERIC(9, 4),
    VALOR_ISS			NUMERIC(9, 2),
    NOTA_IESUBST		VARCHAR(20),
    NOTA_DATASAIDA		TIMESTAMP,
    NOTA_BASEICMS		NUMERIC(9, 4),
    NOTA_BASEICMSSUBST		NUMERIC(9, 4),
    NOTA_VALORICMSSUBST		NUMERIC(9, 2),
    VALOR_IPI                   NUMERIC(9, 2),
    CODVENDEDOR_ABRE		INTEGER,
    DESCONTOTXT                 VARCHAR(40),
    CLI_NOME                    VARCHAR(40),
    CLI_LOGRADOURO              VARCHAR(40),
    CLI_NUMERO                  INTEGER,
    CLI_COMPLEMENTO             VARCHAR(40),
    CLI_BAIRRO                  VARCHAR(60),
    CLI_CEP                     VARCHAR(10),
    CLI_CIDADE                  VARCHAR(60),
    CLI_ESTADO                  VARCHAR(2),
    CLI_FONE                    VARCHAR(20),
    CLI_FAX                     VARCHAR(20),
    CLI_EMAIL                   VARCHAR(50),
    CLI_RGIE                    VARCHAR(20),
    CLI_CPFCGC                  VARCHAR(20),
    TRA_NOME                    VARCHAR(40),
    TRA_LOGRADOURO              VARCHAR(40),
    TRA_NUMERO                  INTEGER,
    TRA_COMPLEMENTO             VARCHAR(40),
    TRA_BAIRRO                  VARCHAR(60),
    TRA_CEP                     VARCHAR(10),
    TRA_CIDADE                  VARCHAR(60),
    TRA_ESTADO                  VARCHAR(2),
    TRA_FONE                    VARCHAR(20),
    TRA_FAX                     VARCHAR(20),
    TRA_EMAIL                   VARCHAR(50),
    TRA_RGIE                    VARCHAR(20),
    TRA_CPFCGC                  VARCHAR(20)
)
AS
    DECLARE VARIABLE TEMP_PESSOAFISICA CHAR(1);
    DECLARE VARIABLE TEMP_RAZAOSOCIAL  VARCHAR(40);
    DECLARE VARIABLE TEMP_IE           VARCHAR(20);
    DECLARE VARIABLE TEMP_CGC          VARCHAR(20);
BEGIN

  SELECT
    ES,
    CODCLIENTE,
    CODFORNECEDOR,
    DATA,
    SERVICOS,
    VALOR_SERVICOS,
    VALOR_ITENS,
    DESCONTO,
    VALOR_PRODUTOS,
    VALOR_ICMS,
    VALOR_TOTAL,
    OBSERVACOES,
    NOTA_NUMERO,
    NOTA_DATAEMISSAO,
    NOTA_CODNATUOPER,
    NOTA_CODTRANSPORTADOR,
    NOTA_PLACAVEICULO,
    NOTA_UFVEICULO,
    NOTA_FRETE,
    NOTA_VALOR_FRETE,
    NOTA_VALOR_SEGURO,
    NOTA_VALOR_OUTROS,
    NOTA_VALOR_TOTAL,
    NOTA_QUANTIDADE,
    NOTA_ESPECIE,
    NOTA_MARCA,
    NOTA_VOLNUM,
    NOTA_PESOBRUTO,
    NOTA_PESOLIQUIDO,
    NOTA_DADOSADICIONAIS,
    CODVENDEDOR,
    STATUS,
    CONDICAO,
    DATAINICIO,
    DATATERMINO,
    ICMSSIMPLES,
    ICMSSIMPALIQ,
    ISSALIQ,
    VALOR_ISS,
    NOTA_IESUBST,
    NOTA_DATASAIDA,
    NOTA_BASEICMS,
    NOTA_BASEICMSSUBST,
    NOTA_VALORICMSSUBST,
    VALOR_IPI,
    CODVENDEDOR_ABRE,
    DESCONTOTXT
  FROM
    MOVIMENTOS MO
  WHERE
    CODIGO = :CODMOVIMENTO
  INTO
    :ES,
    :CODCLIENTE,
    :CODFORNECEDOR,
    :DATA,
    :SERVICOS,
    :VALOR_SERVICOS,
    :VALOR_ITENS,
    :DESCONTO,
    :VALOR_PRODUTOS,
    :VALOR_ICMS,
    :VALOR_TOTAL,
    :OBSERVACOES,
    :NOTA_NUMERO,
    :NOTA_DATAEMISSAO,
    :NOTA_CODNATUOPER,
    :NOTA_CODTRANSPORTADOR,
    :NOTA_PLACAVEICULO,
    :NOTA_UFVEICULO,
    :NOTA_FRETE,
    :NOTA_VALOR_FRETE,
    :NOTA_VALOR_SEGURO,
    :NOTA_VALOR_OUTROS,
    :NOTA_VALOR_TOTAL,
    :NOTA_QUANTIDADE,
    :NOTA_ESPECIE,
    :NOTA_MARCA,
    :NOTA_VOLNUM,
    :NOTA_PESOBRUTO,
    :NOTA_PESOLIQUIDO,
    :NOTA_DADOSADICIONAIS,
    :CODVENDEDOR,
    :STATUS,
    :CONDICAO,
    :DATAINICIO,
    :DATATERMINO,
    :ICMSSIMPLES,
    :ICMSSIMPALIQ,
    :ISSALIQ,
    :VALOR_ISS,
    :NOTA_IESUBST,
    :NOTA_DATASAIDA,
    :NOTA_BASEICMS,
    :NOTA_BASEICMSSUBST,
    :NOTA_VALORICMSSUBST,
    :VALOR_IPI,
    :CODVENDEDOR_ABRE,
    :DESCONTOTXT;

  SELECT
    CL.NOME,
    CL.RAZAOSOCIAL,
    CL.PESSOAFISICA,
    CL.NUMERO,
    CL.COMPLEMENTO,
    CL.ESTADO,
    CL.FONE,
    CL.FAX,
    CL.EMAIL,
    CL.RG,
    CL.CPF,
    CL.IE,
    CL.CGC,
    LO.LOGRADOURO,
    BA.BAIRRO,
    CI.CIDADE,
    LO.CEP
  FROM
    CLIENTES CL
    LEFT JOIN LOGRADOUROS LO ON
      ( LO.CODIGO = CL.LOCALIZACAO AND
        LO.BAIRRO = CL.BAIRRO AND
        LO.CIDADE = CL.CIDADE AND
        LO.ESTADO = CL.ESTADO )
    LEFT JOIN BAIRROS BA ON
      ( BA.CODIGO = CL.BAIRRO AND
        BA.CIDADE = CL.CIDADE AND
        BA.ESTADO = CL.ESTADO )
    LEFT JOIN CIDADES CI ON
      ( CI.CODIGO = CL.CIDADE AND
        CI.ESTADO = CL.ESTADO )
  WHERE
    CL.CODIGO = :CODCLIENTE
  INTO
    :CLI_NOME,
    :TEMP_RAZAOSOCIAL,
    :TEMP_PESSOAFISICA,
    :CLI_NUMERO,
    :CLI_COMPLEMENTO,
    :CLI_ESTADO,
    :CLI_FONE,
    :CLI_FAX,
    :CLI_EMAIL,
    :CLI_RGIE,
    :CLI_CPFCGC,
    :TEMP_IE,
    :TEMP_CGC,
    :CLI_LOGRADOURO,
    :CLI_BAIRRO,
    :CLI_CIDADE,
    :CLI_CEP;

  IF ( TEMP_PESSOAFISICA = 'J' ) THEN
   BEGIN
     CLI_NOME   = TEMP_RAZAOSOCIAL;
     CLI_RGIE   = TEMP_IE;
     CLI_CPFCGC = TEMP_CGC;
   END


  SELECT
    TR.NOME,
    TR.RAZAOSOCIAL,
    TR.PESSOAFISICA,
    TR.NUMERO,
    TR.COMPLEMENTO,
    TR.ESTADO,
    TR.FONE,
    TR.FAX,
    TR.EMAIL,
    TR.RG,
    TR.CPF,
    TR.IE,
    TR.CGC,
    LO.LOGRADOURO,
    BA.BAIRRO,
    CI.CIDADE,
    LO.CEP
  FROM
    TRANSPORTADORES TR
    LEFT JOIN LOGRADOUROS LO ON
      ( LO.CODIGO = TR.LOCALIZACAO AND
        LO.BAIRRO = TR.BAIRRO AND
        LO.CIDADE = TR.CIDADE AND
        LO.ESTADO = TR.ESTADO )
    LEFT JOIN BAIRROS BA ON
      ( BA.CODIGO = TR.BAIRRO AND
        BA.CIDADE = TR.CIDADE AND
        BA.ESTADO = TR.ESTADO )
    LEFT JOIN CIDADES CI ON
      ( CI.CODIGO = TR.CIDADE AND
        CI.ESTADO = TR.ESTADO )
  WHERE
    TR.CODIGO = :CODCLIENTE
  INTO
    :TRA_NOME,
    :TEMP_RAZAOSOCIAL,
    :TEMP_PESSOAFISICA,
    :TRA_NUMERO,
    :TRA_COMPLEMENTO,
    :TRA_ESTADO,
    :TRA_FONE,
    :TRA_FAX,
    :TRA_EMAIL,
    :TRA_RGIE,
    :TRA_CPFCGC,
    :TEMP_IE,
    :TEMP_CGC,
    :TRA_LOGRADOURO,
    :TRA_BAIRRO,
    :TRA_CIDADE,
    :TRA_CEP;

  IF ( TEMP_PESSOAFISICA = 'J' ) THEN
   BEGIN
     TRA_NOME   = TEMP_RAZAOSOCIAL;
     TRA_RGIE   = TEMP_IE;
     TRA_CPFCGC = TEMP_CGC;
   END


 SUSPEND;

END!

GRANT EXECUTE ON PROCEDURE REL_NOTACORPO TO PUBLIC!

CREATE PROCEDURE REL_NOTADUP (
   CODMOVIMENTO  INTEGER
)
RETURNS (
   MOVIMENTO            INTEGER,
   NUMERO       	SMALLINT,
   DESCRICAO    	VARCHAR(40),
   DATACADAST   	TIMESTAMP,
   VALOR        	NUMERIC(9, 2),
   DATAVENCIMENTO 	TIMESTAMP
)
AS
BEGIN

   FOR
   SELECT
     NUMERO,
     DESCRICAO,
     DATACADAST,
     VALOR,
     DATAVENCIMENTO
   FROM
     PAGAMENTOS
   WHERE
     CODMOVIMENTO = :CODMOVIMENTO AND
     ES = 2
   INTO
     :NUMERO,
     :DESCRICAO,
     :DATACADAST,
     :VALOR,
     :DATAVENCIMENTO
   DO
   BEGIN
     MOVIMENTO = CODMOVIMENTO;
     SUSPEND;
   END


END!

GRANT EXECUTE ON PROCEDURE REL_NOTADUP TO PUBLIC!

CREATE PROCEDURE REL_NOTAPRO (
   CODMOVIMENTO  INTEGER
)
RETURNS (
   CODIGO               INTEGER,
   BARRA                CHAR(13),
   DESCRICAO1           VARCHAR(40),
   DESCRICAO2           VARCHAR(60),
   SERIE                VARCHAR(20),
   VALOR_VENDA          NUMERIC(9, 2),
   ICMS_VENDA           NUMERIC(9, 2),
   DESCONTO             NUMERIC(9, 2),
   QUANTIDADE           NUMERIC(9, 2),
   VALOR_PAGO           NUMERIC(9, 2),
   VALOR_ICMS           NUMERIC(9, 2),
   SITTRIBU             CHAR(3)
)
AS
BEGIN

   FOR
   SELECT
     ID.CODPRODUTO,
     ID.BARRA,
     PO.DESCRICAO,
     ID.SERIE,
     ID.VALOR_VENDA,
     ID.ICMSVENDA,
     ID.DESCONTO,
     ID.QUANTIDADE,
     ID.VALOR_PAGO,
     ID.VALOR_ICMS,
     TI.SITTRIBU
   FROM
     INDIVIDUAIS ID
     LEFT JOIN PRODUTOS PO ON
       ( PO.CODIGO = ID.CODPRODUTO )
     LEFT JOIN TEMPITENS TI ON
       ( TI.CODMOVIMENTO = ID.CODMOVENTRADA AND
         TI.CODPRODUTO   = ID.CODPRODUTO    AND
         TI.CODIGO       = ID.CODITEM )
   WHERE
     ID.CODMOVSAIDA = :CODMOVIMENTO AND
     ID.VENDIDO = 'S' AND
     ID.PS = 'P'
   INTO
     :CODIGO,
     :BARRA,
     :DESCRICAO1,
     :SERIE,
     :VALOR_VENDA,
     :ICMS_VENDA,
     :DESCONTO,
     :QUANTIDADE,
     :VALOR_PAGO,
     :VALOR_ICMS,
     :SITTRIBU
   DO
   BEGIN
     DESCRICAO2 = DESCRICAO1 || ' ' || SERIE;
     SUSPEND;
   END

END!

GRANT EXECUTE ON PROCEDURE REL_NOTAPRO TO PUBLIC!

CREATE PROCEDURE REL_NOTASER (
   CODMOVIMENTO  INTEGER
)
RETURNS (
   CODIGO               INTEGER,
   BARRA                CHAR(13),
   DESCRICAO1           VARCHAR(40),
   DESCRICAO2           VARCHAR(60),
   SERIE                VARCHAR(20),
   VALOR_VENDA          NUMERIC(9, 2),
   ICMS_VENDA           NUMERIC(9, 2),
   DESCONTO             NUMERIC(9, 2),
   QUANTIDADE           NUMERIC(9, 2),
   VALOR_PAGO           NUMERIC(9, 2),
   VALOR_ICMS           NUMERIC(9, 2),
   SITTRIBU             CHAR(3)
)
AS
BEGIN

   FOR
   SELECT
     ID.CODPRODUTO,
     ID.BARRA,
     PO.DESCRICAO,
     ID.SERIE,
     ID.VALOR_VENDA,
     ID.ICMSVENDA,
     ID.DESCONTO,
     ID.QUANTIDADE,
     ID.VALOR_PAGO,
     ID.VALOR_ICMS,
     TI.SITTRIBU
   FROM
     INDIVIDUAIS ID
     LEFT JOIN PRODUTOS PO ON
       ( PO.CODIGO = ID.CODPRODUTO )
     LEFT JOIN TEMPITENS TI ON
       ( TI.CODMOVIMENTO = ID.CODMOVENTRADA AND
         TI.CODPRODUTO   = ID.CODPRODUTO    AND
         TI.CODIGO       = ID.CODITEM )
   WHERE
     ID.CODMOVSAIDA = :CODMOVIMENTO AND
     ID.VENDIDO = 'S' AND
     ID.PS = 'S'
   INTO
     :CODIGO,
     :BARRA,
     :DESCRICAO1,
     :SERIE,
     :VALOR_VENDA,
     :ICMS_VENDA,
     :DESCONTO,
     :QUANTIDADE,
     :VALOR_PAGO,
     :VALOR_ICMS,
     :SITTRIBU
   DO
   BEGIN
     DESCRICAO2 = DESCRICAO1 || ' ' || SERIE;
     SUSPEND;
   END

END!

GRANT EXECUTE ON PROCEDURE REL_NOTASER TO PUBLIC!



