
CREATE TABLE EMPREENDIMENTOS (
   CODIGO           INTEIRO_VALIDO,
   NOME             STR40_VALIDO,
   SALARIO          DINHEIRO,
   CONSTRAINT       EMPREENDIMENTOS_PK
   PRIMARY KEY      (CODIGO)
)!

GRANT ALL ON EMPREENDIMENTOS TO PUBLIC!

CREATE TABLE AREASEMP (
   CODEMP           INTEIRO_VALIDO,
   CODBAIRRO        INTEIRO_VALIDO,
   CODCIDADE        INTEIRO_VALIDO,
   ESTADO           STR02_VALIDO,
   CONSTRAINT       AREASEMP_PK
   PRIMARY KEY      (CODEMP, CODBAIRRO, CODCIDADE, ESTADO),
   CONSTRAINT       AREASEMP_FK01
   FOREIGN KEY      (CODBAIRRO, CODCIDADE, ESTADO)
   REFERENCES       BAIRROS (CODIGO, CIDADE, ESTADO)
)!

GRANT ALL ON AREASEMP TO PUBLIC!

CREATE TABLE AREASCLI (
   CODCLI           INTEIRO_VALIDO,
   CODBAIRRO        INTEIRO_VALIDO,
   CODCIDADE        INTEIRO_VALIDO,
   ESTADO           STR02_VALIDO,
   CONSTRAINT       AREASCLI_PK
   PRIMARY KEY      (CODCLI, CODBAIRRO, CODCIDADE, ESTADO),
   CONSTRAINT       AREASCLI_FK01
   FOREIGN KEY      (CODBAIRRO, CODCIDADE, ESTADO)
   REFERENCES       BAIRROS (CODIGO, CIDADE, ESTADO)
)!
  
GRANT ALL ON AREASCLI TO PUBLIC!

ALTER TABLE CLIENTES ADD   PROTESTO         SIMNAO!
ALTER TABLE CLIENTES ADD   SPC              SIMNAO!
ALTER TABLE CLIENTES ADD   SERASA           SIMNAO!
ALTER TABLE CLIENTES ADD   IMOVEL           SIMNAO!
ALTER TABLE CLIENTES ADD   PROTESTO_DATA    TIMESTAMP!
ALTER TABLE CLIENTES ADD   SPC_DATA         TIMESTAMP!
ALTER TABLE CLIENTES ADD   SERASA_DATA      TIMESTAMP!
ALTER TABLE CLIENTES ADD   PROTESTO_USER    STR20!
ALTER TABLE CLIENTES ADD   SPC_USER         STR20!
ALTER TABLE CLIENTES ADD   SERASA_USER      STR20!
ALTER TABLE CLIENTES ADD   IMOVEL_TIPO      STR20!
ALTER TABLE CLIENTES ADD   CODEMPREEND      INTEIRO!
ALTER TABLE CLIENTES ADD   PROCESSO_OK      SIMNAO!

ALTER TABLE CLIENTES ADD
   CONSTRAINT CLIENTES_FK02
   FOREIGN KEY (CODEMPREEND) 
   REFERENCES EMPREENDIMENTOS (CODIGO)!

ALTER TABLE CLIENTES ADD   FGTS             SIMNAO!
ALTER TABLE CLIENTES ADD   PIS              STR20!
ALTER TABLE CLIENTES ADD   VALOR_FGTS       DINHEIRO!


 