/* ALTERACOES DA 2001 */

ALTER TABLE VENDEDORES ADD NOMEUSER STR30_VALIDO!
ALTER TABLE VENDEDORES ADD DESCONTO DINHEIRO!

UPDATE VENDEDORES SET NOMEUSER = 'SYSDBA'!
UPDATE VENDEDORES SET DESCONTO = 0!

CREATE TABLE OS_VENDER (
	CODMOVIMENTO		INTEIRO_VALIDO,
	CODVENDEDOR		INTEIRO_VALIDO,
	DATAINI			TIMESTAMP,
	DATAFIM			TIMESTAMP,
	PORCENTAGEM		DINHEIRO,
	CONSTRAINT		OS_VENDER_PK
	PRIMARY KEY		(CODMOVIMENTO, CODVENDEDOR),
	CONSTRAINT		OS_VENDER_FK01
	FOREIGN KEY		(CODMOVIMENTO)
	REFERENCES		MOVIMENTOS (CODIGO)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT		OS_VENDER_FK02
	FOREIGN KEY		(CODVENDEDOR)
	REFERENCES		VENDEDORES (CODIGO)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)!

GRANT ALL ON OS_VENDER TO PUBLIC!


