CREATE TABLE CLI_FILES (
   CODIGO     INTEIRO_VALIDO,
   CODCLIENTE INTEIRO_VALIDO,
   NOME       STR60_VALIDO,
   TAMANHO    INTEIRO_PADRAO,
   DATA       TIMESTAMP,
   USUARIO    STR30,
   CONTEUDO   BLOB,
   CONSTRAINT CLI_FILES_PK
   PRIMARY KEY (CODIGO),
   CONSTRAINT CLI_FILES_FK01
   FOREIGN KEY (CODCLIENTE)
   REFERENCES CLIENTES
   ON UPDATE CASCADE
)!

GRANT ALL ON CLI_FILES TO PUBLIC!

INSERT INTO SEQUENCIA (CODIGO, TABELA, SEQUENCIA)
   VALUES (31, 'CLI_FILES', 1)!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (39, CURRENT_TIMESTAMP)!
