CREATE TABLE PRO_FILES (
   CODIGO     INTEIRO_VALIDO,
   CODPRODUTO INTEIRO_VALIDO,
   NOME       STR60_VALIDO,
   TAMANHO    INTEIRO_PADRAO,
   DATA       TIMESTAMP,
   USUARIO    STR30,
   ORIGINAL VARCHAR(255),
   CONTEUDO   BLOB,
   CONSTRAINT PRO_FILES_PK
   PRIMARY KEY (CODIGO),
   CONSTRAINT PRO_FILES_FK01
   FOREIGN KEY (CODPRODUTO)
   REFERENCES PRODUTOS
   ON UPDATE CASCADE
)!

GRANT ALL ON PRO_FILES TO PUBLIC!

INSERT INTO SEQUENCIA (CODIGO, TABELA, SEQUENCIA)
   VALUES (32, 'PRO_FILES', 1)!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (41, CURRENT_TIMESTAMP)!
