ALTER TABLE MOVIMENTOS DROP CONSTRAINT MOVIMENTOS_FK02!

ALTER TABLE MOVIMENTOS DROP CONSTRAINT MOVIMENTOS_FK03!

ALTER TABLE MOVIMENTOS DROP CONSTRAINT MOVIMENTOS_FK04!

CREATE PROCEDURE CONFIGURA_MOVIMENTOS
AS
DECLARE VARIABLE CODIGO                INTEGER;
DECLARE VARIABLE CODCLIENTE            INTEGER;
DECLARE VARIABLE CODFORNECEDOR         INTEGER;
DECLARE VARIABLE CODVENDEDOR           INTEGER;
DECLARE VARIABLE CODVENDEDOR_ABRE      INTEGER;
DECLARE VARIABLE NOTA_CODTRANSPORTADOR INTEGER;
DECLARE VARIABLE CODRESPONSAVEL        INTEGER;
BEGIN

  FOR
  SELECT
    CODIGO,
    CODCLIENTE,
    CODFORNECEDOR,
    CODVENDEDOR,
    CODVENDEDOR_ABRE,
    NOTA_CODTRANSPORTADOR,
    CODRESPONSAVEL
  FROM
    MOVIMENTOS
  INTO
    :CODIGO,
    :CODCLIENTE,
    :CODFORNECEDOR,
    :CODVENDEDOR,
    :CODVENDEDOR_ABRE,
    :NOTA_CODTRANSPORTADOR,
    :CODRESPONSAVEL
  DO
  BEGIN

    IF (CODFORNECEDOR IS NOT NULL) THEN
      SELECT
        CODIGO
      FROM
        CLIENTES
      WHERE
        CODFORNECEDOR = :CODFORNECEDOR
      INTO
        :CODCLIENTE;

    IF (CODVENDEDOR IS NOT NULL) THEN
      SELECT
        CODIGO
      FROM
        CLIENTES
      WHERE
        CODASSOCIADO = :CODVENDEDOR
      INTO
        :CODVENDEDOR;

    IF (CODVENDEDOR_ABRE IS NOT NULL) THEN
      SELECT
        CODIGO
      FROM
        CLIENTES
      WHERE
        CODASSOCIADO = :CODVENDEDOR_ABRE
      INTO
        :CODVENDEDOR_ABRE;

    IF (NOTA_CODTRANSPORTADOR IS NOT NULL) THEN
      SELECT
        CODIGO
      FROM
        CLIENTES
      WHERE
        CODTRANSPORTADOR = :NOTA_CODTRANSPORTADOR
      INTO
        :NOTA_CODTRANSPORTADOR;

    IF (CODRESPONSAVEL IS NOT NULL) THEN
      SELECT
        CODIGO
      FROM
        CLIENTES
      WHERE
        CODASSOCIADO = :CODRESPONSAVEL
      INTO
        :CODRESPONSAVEL;

    UPDATE
      MOVIMENTOS
    SET
      CODCLIENTE = :CODCLIENTE,
      CODVENDEDOR = :CODVENDEDOR,
      CODVENDEDOR_ABRE = :CODVENDEDOR_ABRE,
      NOTA_CODTRANSPORTADOR = :NOTA_CODTRANSPORTADOR,
      CODRESPONSAVEL = :CODRESPONSAVEL
    WHERE
      CODIGO = :CODIGO;

  END

END!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (49, CURRENT_TIMESTAMP)!