CREATE PROCEDURE WEBGRID_ESTOQUE(
BUSCA VARCHAR (40),
CODEMPRESA INTEGER)
RETURNS (
BARRA VARCHAR(14),
DESCRICAO VARCHAR (60),
LOCAL NUMERIC(9, 2),
TOTAL NUMERIC(9, 2),
VALOR NUMERIC(9, 2))
as
  DECLARE VARIABLE N INTEGER;
BEGIN

  N = 0;

  FOR
  SELECT
    BARRA,
    DESCRICAO,
    ESTOQUELOCAL,
    QUANTIDADE,
    PRECOVENDA
  FROM
    P_PRODUTOS(:CODEMPRESA)
  WHERE
    DESCRICAO LIKE :BUSCA
  ORDER BY
    DESCRICAO
  INTO
    :BARRA,
    :DESCRICAO,
    :LOCAL,
    :TOTAL,
    :VALOR
  DO
  BEGIN

    N = N + 1;
    IF (N > 50) THEN
      EXIT;
    ELSE
      SUSPEND;

  END

END!

GRANT EXECUTE ON PROCEDURE WEBGRID_ESTOQUE TO PUBLIC!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (56, CURRENT_TIMESTAMP)!