
/* APOS ESTE SCRIPT EH RECOMENDADO RODAR UM BACKUP-RESTORE */

UPDATE RDB$RELATION_FIELDS SET
RDB$FIELD_SOURCE = 'INTEIRO_VALIDO',
RDB$NULL_FLAG = 1
WHERE (RDB$FIELD_NAME = 'CODCLIENTE') AND
(RDB$RELATION_NAME = 'MOVIMENTOS')!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (59, CURRENT_TIMESTAMP)!
