/*
** INDICE PARA AGILIZAR PROCEDURES E JOINS
*/

CREATE INDEX RDB$INDEX_ELIESER_01
ON RDB$RELATION_CONSTRAINTS (RDB$RELATION_NAME)!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (62, CURRENT_TIMESTAMP)!
