/*
** ANOTAÇAO DE CUPOM FISCAL (ECF) NA PROCEDURE P_OS
*/

ALTER PROCEDURE P_OS (
    EMPRESA INTEGER)
RETURNS (
    CODIGO INTEGER,
    DATA TIMESTAMP,
    PRIORIDADE INTEGER,
    STATUS VARCHAR (20),
    NOTA_NUMERO INTEGER,
    NOME VARCHAR (40),
    SERIE VARCHAR (30),
    VALOR_TOTAL NUMERIC (9, 2),
    VALOR_ABERTO NUMERIC (9, 2),
    TIPO INTEGER,
    ECF CHAR(1))
AS
BEGIN
  FOR
  SELECT
    MO.CODIGO,
    MO.SERIE,
    MO.VALOR_TOTAL,
    MO.TIPO,
    MO.DATA,
    MO.PRIORIDADE,
    MO.STATUS,
    MO.NOTA_NUMERO,
    MO.ECF,
    CL.NOME
  FROM
    MOVIMENTOS MO
    LEFT JOIN CLIENTES CL ON
      (MO.CODCLIENTE = CL.CODIGO)
  WHERE
    MO.TIPO IN (0, 1, 2, 3, 5, 6, 9) AND
    MO.CODEMPRESA = :EMPRESA
  INTO
    :CODIGO,
    :SERIE,
    :VALOR_TOTAL,
    :TIPO,
    :DATA,
    :PRIORIDADE,
    :STATUS,
    :NOTA_NUMERO,
    :ECF,
    :NOME
  DO
  BEGIN
    VALOR_ABERTO = NULL;
    /* VERIFICO SE ESTA FECHADA A SAIDA */
    IF (TIPO IN (1, 3, 6)) THEN
     BEGIN
       SELECT
         SUM(VALOR)
       FROM
         PAGAMENTOS
       WHERE
         CODMOVIMENTO = :CODIGO AND
         PAGO = 0
       INTO
         :VALOR_ABERTO;
     END
    /* RETORNO */
    SUSPEND;
  END
END!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (64, CURRENT_TIMESTAMP)!
