/*
** EXIBIÇAO DA QUANTIDADE NA INTERNET
*/

ALTER PROCEDURE WEBGRID_ESTOQUE (
    BUSCA VARCHAR (40),
    CODEMPRESA INTEGER)
RETURNS (
    BARRA VARCHAR (14),
    DESCRICAO VARCHAR (60),
    QUANTIDADE NUMERIC (9, 2),
    VALOR NUMERIC (9, 2))
AS
  DECLARE VARIABLE N INTEGER;
BEGIN

  N = 0;

  FOR
  SELECT
    PO.BARRA,
    PO.DESCRICAO,
    PO.PRECOVENDA,
    SUM(ID.QUANTIDADE)
  FROM
    PRODUTOS PO
    LEFT JOIN INDIVIDUAIS ID ON
      (ID.CODPRODUTO = PO.CODIGO)
  WHERE
    PO.DESCRICAO LIKE :BUSCA AND
    PO.PS = 'P' AND
    ID.CODEMPRESA = :CODEMPRESA AND
    ID.VENDIDO = 'N'
  GROUP BY
    PO.BARRA,
    PO.DESCRICAO,
    PO.PRECOVENDA
  ORDER BY
    PO.DESCRICAO
  INTO
    :BARRA,
    :DESCRICAO,
    :VALOR,
    :QUANTIDADE
  DO
  BEGIN

    if (QUANTIDADE IS NULL) then
      QUANTIDADE = 0.0;

    N = N + 1;
    IF (N > 50) THEN
      EXIT;
    ELSE
      SUSPEND;

  END

END!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (66, CURRENT_TIMESTAMP)!

