/*
** ADIONAIS NO DOCUMENTO
*/

CREATE DOMAIN DOCUMENTO_PAG CHAR(1) DEFAULT 'A' NOT NULL
   CHECK(VALUE IN ('A', 'V'))!

CREATE DOMAIN DOCUMENTO_DOC CHAR(1) DEFAULT 'D' NOT NULL
   CHECK(VALUE IN ('D', 'C', 'B', 'O'))!

ALTER TABLE DOCUMENTOS ADD TIPO_PAG DOCUMENTO_PAG!

ALTER TABLE DOCUMENTOS ADD TIPO_DOC DOCUMENTO_DOC!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (68, CURRENT_TIMESTAMP)!
