/*
** ADIONAIS NO PAGAMENTO
*/

ALTER TABLE PAGAMENTOS ADD TIPO_PAG DOCUMENTO_PAG!

ALTER TABLE PAGAMENTOS ADD TIPO_DOC DOCUMENTO_DOC!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (69, CURRENT_TIMESTAMP)!