/*
** ADIONAIS NO PAGAMENTO
*/

ALTER TABLE PAGAMENTOS ADD CH_BANCO   INTEIRO!

ALTER TABLE PAGAMENTOS ADD CH_AGENCIA INTEIRO!

ALTER TABLE PAGAMENTOS ADD CH_CONTA   INTEIRO!

ALTER TABLE PAGAMENTOS ADD CH_SERIE   STR10!

ALTER TABLE PAGAMENTOS ADD CH_NUMERO  INTEIRO!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (71, CURRENT_TIMESTAMP)!
