/*
** COMISSIONAMENTO DE SERVICOS
*/

UPDATE RDB$RELATION_FIELDS SET
RDB$FIELD_SOURCE = 'DATA_VALIDA',
RDB$NULL_FLAG = 1
WHERE (RDB$FIELD_NAME = 'DATAINI') AND
(RDB$RELATION_NAME = 'OS_VENDER')!

UPDATE RDB$RELATION_FIELDS SET
RDB$FIELD_SOURCE = 'DATA_VALIDA',
RDB$NULL_FLAG = 1
WHERE (RDB$FIELD_NAME = 'DATAFIM') AND
(RDB$RELATION_NAME = 'OS_VENDER')!

ALTER TABLE OS_VENDER DROP CONSTRAINT OS_VENDER_PK!

ALTER TABLE OS_VENDER
ADD CONSTRAINT OS_VENDER_PK
PRIMARY KEY (CODMOVIMENTO, CODVENDEDOR, DATAINI)!

ALTER TABLE OS_VENDER
ADD TOTAL_SERVICOS DINHEIRO
NOT NULL!

UPDATE OS_VENDER SET TOTAL_SERVICOS = '0'!

ALTER TABLE OS_VENDER
ADD VALOR_SERVICO COMPUTED BY ((TOTAL_SERVICOS * PORCENTAGEM) / 100)!

ALTER TABLE OS_VENDER
ADD COMISSAO DINHEIRO
NOT NULL!

UPDATE OS_VENDER SET COMISSAO = '0'!

ALTER TABLE OS_VENDER
ADD VALOR_COMISSAO COMPUTED BY ((VALOR_SERVICO * COMISSAO) / 100)!

CREATE TRIGGER OS_VENDER_BI0 FOR OS_VENDER
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  /* TRIGGER TEXT */
  SELECT
    COMISSAO
  FROM
    CLIENTES
  WHERE
    CODIGO = NEW.CODVENDEDOR
  INTO
    NEW.COMISSAO;
END!

CREATE TRIGGER OS_VENDER_BU0 FOR OS_VENDER
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  /* TRIGGER TEXT */
  SELECT
    COMISSAO
  FROM
    CLIENTES
  WHERE
    CODIGO = NEW.CODVENDEDOR
  INTO
    NEW.COMISSAO;
END!

ALTER PROCEDURE AUTOBAIXA (
    CODMOVIMENTO INTEGER)
AS
DECLARE VARIABLE CODDOC_AVISTA INTEGER;
DECLARE VARIABLE CODIGO INTEGER;
DECLARE VARIABLE CODDOCUMENTO INTEGER;
DECLARE VARIABLE DATAVENCIMENTO TIMESTAMP;
DECLARE VARIABLE PAGO INTEGER;
DECLARE VARIABLE PARCELA_TOTAL NUMERIC(9,2);
DECLARE VARIABLE MOVIMENTO_TOTAL NUMERIC(9,2);
DECLARE VARIABLE VALOR_COMISSAO NUMERIC(9,2);
DECLARE VARIABLE XPARC INTEGER;
DECLARE VARIABLE CODEMPRESA INTEGER;
DECLARE VARIABLE CLIENTE_COMISSIONADO CHAR(1);
DECLARE VARIABLE VALOR_SERVICO NUMERIC(9, 2);
DECLARE VARIABLE PRODUTO_COMISSIONADO CHAR(1);
DECLARE VARIABLE TOTAL_SERVICOS_COMIS NUMERIC(9, 2);
BEGIN
  /* VERIFICO SE OS VALORES SAO CORRESPONDENTES */
  SELECT
    COUNT(CODIGO),
    SUM(VALOR)
  FROM
    PAGAMENTOS
  WHERE
    CODMOVIMENTO = :CODMOVIMENTO
  INTO
    :XPARC,
    :PARCELA_TOTAL;

  /* COMISSIONAMENTO DE VENDEDORES */
  SELECT
    NOTA_VALOR_TOTAL,
    VALOR_COMISSAO,
    CODEMPRESA
  FROM
    MOVIMENTOS
  WHERE
    CODIGO = :CODMOVIMENTO
  INTO
    :MOVIMENTO_TOTAL,
    :VALOR_COMISSAO,
    :CODEMPRESA;

  /* CALCULO A COMISSAO DE CADA PARCELA, COM SEGURANCA */
  IF (VALOR_COMISSAO IS NULL) THEN
    VALOR_COMISSAO = 0;
  IF (XPARC IS NULL) THEN
    XPARC = 0;

  IF ((VALOR_COMISSAO > 0) AND (XPARC > 0)) THEN
    VALOR_COMISSAO = (VALOR_COMISSAO / CAST(XPARC AS NUMERIC(9,2)));

  IF (MOVIMENTO_TOTAL > PARCELA_TOTAL) THEN
    EXCEPTION VALOR_PARCELA;

  /**/
  /**  COMISSIONAMENTO DE SERVIÇOS */
  /**/
  TOTAL_SERVICOS_COMIS = 0;

  SELECT
    CL.COMISSIONADO
  FROM
    CLIENTES CL
    JOIN MOVIMENTOS MO ON
      (CL.CODIGO = MO.CODCLIENTE)
  WHERE
    MO.CODIGO = :CODMOVIMENTO
  INTO
    :CLIENTE_COMISSIONADO;

  IF (CLIENTE_COMISSIONADO = 'S') THEN
   BEGIN

     FOR
     SELECT
       ID.VALOR_PAGO,
       PO.COMISSIONADO
     FROM
       INDIVIDUAIS ID
       JOIN PRODUTOS PO ON
         (ID.CODPRODUTO = PO.CODIGO)
     WHERE
       ID.CODMOVSAIDA = :CODMOVIMENTO AND
       ID.VENDIDO = 'S' AND
       PO.PS = 'S'
     INTO
       :VALOR_SERVICO,
       :PRODUTO_COMISSIONADO
     DO
     IF (PRODUTO_COMISSIONADO = 'S') THEN
       TOTAL_SERVICOS_COMIS = TOTAL_SERVICOS_COMIS + VALOR_SERVICO;

     UPDATE
       OS_VENDER
     SET
       TOTAL_SERVICOS = :TOTAL_SERVICOS_COMIS
     WHERE
       CODMOVIMENTO = :CODMOVIMENTO;

   END

  /* QUAL É O DOCUMENTO A VISTA? */
  SELECT
    CODDOC_AVISTA
  FROM
    SISCONFIG
  WHERE
    CODIGO = :CODEMPRESA
  INTO
    :CODDOC_AVISTA;

  /* PROCURO OS PAGAMENTOS, ALGUM É A VISTA? */
  FOR
  SELECT
    CODIGO,
    CODDOCUMENTO,
    DATAVENCIMENTO,
    PAGO
  FROM
    PAGAMENTOS
  WHERE
    CODMOVIMENTO = :CODMOVIMENTO
  INTO
    :CODIGO,
    :CODDOCUMENTO,
    :DATAVENCIMENTO,
    :PAGO
  DO
  BEGIN
    /* ATUALIZO A COMISSAO */
    UPDATE
      PAGAMENTOS
    SET
      VALOR_COMISSAO = :VALOR_COMISSAO
    WHERE
      CODIGO = :CODIGO;
    /* O DOCUMENTO É A VISTA? */
    IF ((CODDOCUMENTO = CODDOC_AVISTA) AND (PAGO = 0)) THEN
     BEGIN
      /* FAÇO O LANÇAMENTO */
      UPDATE
        PAGAMENTOS
      SET
        PAGO = 1
      WHERE
        CODIGO = :CODIGO;
     END
  END
END!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (72, CURRENT_TIMESTAMP)!
