/*
** TIPO DA OS
*/

CREATE TABLE OSTIPOS (
  CODIGO INTEIRO_VALIDO,
  TIPO STR40_VALIDO,
  CONSTRAINT OSTIPOS_PK
  PRIMARY KEY (CODIGO))!
  
GRANT ALL ON OSTIPOS TO PUBLIC!

ALTER TABLE MOVIMENTOS ADD OSTIPO INTEIRO!

INSERT INTO
  SEQUENCIA(CODIGO, TABELA, SEQUENCIA)
  VALUES(33, 'OSTIPOS', 10)!

ALTER TABLE MOVIMENTOS ADD
  CONSTRAINT MOVIMENTOS_FK09
  FOREIGN KEY (OSTIPO)
  REFERENCES OSTIPOS(CODIGO)
  ON UPDATE CASCADE!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (75, CURRENT_TIMESTAMP)!
