/*
** BANCOS
*/

CREATE TABLE BANCOS (
  CODIGO INTEIRO_VALIDO,
  NOME STR60_VALIDO,
  CONSTRAINT BANCOS_PK
  PRIMARY KEY (CODIGO))!
  
GRANT ALL ON BANCOS TO PUBLIC!

ALTER TABLE PAGAMENTOS ADD
  CONSTRAINT PAGAMENTOS_FK04
  FOREIGN KEY (CH_BANCO)
  REFERENCES BANCOS(CODIGO)
  ON UPDATE CASCADE!

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (76, CURRENT_TIMESTAMP)!
